<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_completion/workflow_completion.proto

namespace Coresdk\WorkflowCompletion;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Successful workflow activation with a list of commands generated by the workflow execution
 *
 * Generated from protobuf message <code>coresdk.workflow_completion.Success</code>
 */
class Success extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of commands to send back to the temporal server
     *
     * Generated from protobuf field <code>repeated .coresdk.workflow_commands.WorkflowCommand commands = 1;</code>
     */
    private $commands;
    /**
     * Any internal flags which the lang SDK used in the processing of this activation
     *
     * Generated from protobuf field <code>repeated uint32 used_internal_flags = 6;</code>
     */
    private $used_internal_flags;
    /**
     * The versioning behavior this workflow is currently using
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.VersioningBehavior versioning_behavior = 7;</code>
     */
    protected $versioning_behavior = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Coresdk\WorkflowCommands\WorkflowCommand>|\Google\Protobuf\Internal\RepeatedField $commands
     *           A list of commands to send back to the temporal server
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $used_internal_flags
     *           Any internal flags which the lang SDK used in the processing of this activation
     *     @type int $versioning_behavior
     *           The versioning behavior this workflow is currently using
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowCompletion\WorkflowCompletion::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of commands to send back to the temporal server
     *
     * Generated from protobuf field <code>repeated .coresdk.workflow_commands.WorkflowCommand commands = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCommands()
    {
        return $this->commands;
    }

    /**
     * A list of commands to send back to the temporal server
     *
     * Generated from protobuf field <code>repeated .coresdk.workflow_commands.WorkflowCommand commands = 1;</code>
     * @param array<\Coresdk\WorkflowCommands\WorkflowCommand>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCommands($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Coresdk\WorkflowCommands\WorkflowCommand::class);
        $this->commands = $arr;

        return $this;
    }

    /**
     * Any internal flags which the lang SDK used in the processing of this activation
     *
     * Generated from protobuf field <code>repeated uint32 used_internal_flags = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsedInternalFlags()
    {
        return $this->used_internal_flags;
    }

    /**
     * Any internal flags which the lang SDK used in the processing of this activation
     *
     * Generated from protobuf field <code>repeated uint32 used_internal_flags = 6;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsedInternalFlags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->used_internal_flags = $arr;

        return $this;
    }

    /**
     * The versioning behavior this workflow is currently using
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.VersioningBehavior versioning_behavior = 7;</code>
     * @return int
     */
    public function getVersioningBehavior()
    {
        return $this->versioning_behavior;
    }

    /**
     * The versioning behavior this workflow is currently using
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.VersioningBehavior versioning_behavior = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setVersioningBehavior($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\VersioningBehavior::class);
        $this->versioning_behavior = $var;

        return $this;
    }

}

