<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflow/v1/message.proto

namespace Temporal\Api\Workflow\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Configuration for time skipping during a workflow execution.
 * When enabled, virtual time advances automatically whenever there is no in-flight work.
 * In-flight work includes activities, child workflows, Nexus operations, signal/cancel external workflow operations,
 * and possibly other features added in the future.
 * User timers are not classified as in-flight work and will be skipped over.
 * When time advances, it skips to the earlier of the next user timer or the configured bound, if either exists.
 * 
 * Propagation behavior of time skipping:
 * The enabled flag, bound fields, and accumulated skipped duration are propagated to related executions as follows:
 * (1) Child workflows and continue-as-new: both the configuration and the accumulated skipped duration are
 *     inherited from the current execution. The configured bound is shared between the inherited skipped
 *     duration and any additional duration skipped by the new run.
 * (2) Retry and cron: the configuration and accumulated skipped duration are inherited as recorded when the
 *     current workflow started; the accumulated skipped duration of the current run is not propagated.
 * (3) Reset: the new run retains the time-skipping configuration of the current execution. Because reset replays
 *     all events up to the reset point and re-applies any UpdateWorkflowExecutionOptions changes made after that
 *     point, the resulting run ends up with the same final time-skipping configuration as the previous run.
 *
 * Generated from protobuf message <code>temporal.api.workflow.v1.TimeSkippingConfig</code>
 */
class TimeSkippingConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Enables or disables time skipping for this workflow execution.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    protected $enabled = false;
    protected $bound;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           Enables or disables time skipping for this workflow execution.
     *     @type \Google\Protobuf\Duration $max_skipped_duration
     *           Maximum total virtual time that can be skipped.
     *     @type \Google\Protobuf\Duration $max_elapsed_duration
     *           Maximum elapsed time since time skipping was enabled.
     *           This includes both skipped time and real time elapsing.
     *           (-- api-linter: core::0142::time-field-names=disabled --)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflow\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Enables or disables time skipping for this workflow execution.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Enables or disables time skipping for this workflow execution.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Maximum total virtual time that can be skipped.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration max_skipped_duration = 4;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getMaxSkippedDuration()
    {
        return $this->readOneof(4);
    }

    public function hasMaxSkippedDuration()
    {
        return $this->hasOneof(4);
    }

    /**
     * Maximum total virtual time that can be skipped.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration max_skipped_duration = 4;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setMaxSkippedDuration($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Maximum elapsed time since time skipping was enabled.
     * This includes both skipped time and real time elapsing.
     * (-- api-linter: core::0142::time-field-names=disabled --)
     *
     * Generated from protobuf field <code>.google.protobuf.Duration max_elapsed_duration = 5;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getMaxElapsedDuration()
    {
        return $this->readOneof(5);
    }

    public function hasMaxElapsedDuration()
    {
        return $this->hasOneof(5);
    }

    /**
     * Maximum elapsed time since time skipping was enabled.
     * This includes both skipped time and real time elapsing.
     * (-- api-linter: core::0142::time-field-names=disabled --)
     *
     * Generated from protobuf field <code>.google.protobuf.Duration max_elapsed_duration = 5;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setMaxElapsedDuration($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getBound()
    {
        return $this->whichOneof("bound");
    }

}

