<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/common/common.proto

namespace Coresdk\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Identifying information about a particular workflow execution, including namespace
 *
 * Generated from protobuf message <code>coresdk.common.NamespacedWorkflowExecution</code>
 */
class NamespacedWorkflowExecution extends \Google\Protobuf\Internal\Message
{
    /**
     * Namespace the workflow run is located in
     *
     * Generated from protobuf field <code>string namespace = 1;</code>
     */
    protected $namespace = '';
    /**
     * Can never be empty
     *
     * Generated from protobuf field <code>string workflow_id = 2;</code>
     */
    protected $workflow_id = '';
    /**
     * May be empty if the most recent run of the workflow with the given ID is being targeted
     *
     * Generated from protobuf field <code>string run_id = 3;</code>
     */
    protected $run_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *           Namespace the workflow run is located in
     *     @type string $workflow_id
     *           Can never be empty
     *     @type string $run_id
     *           May be empty if the most recent run of the workflow with the given ID is being targeted
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\Common\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Namespace the workflow run is located in
     *
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Namespace the workflow run is located in
     *
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Can never be empty
     *
     * Generated from protobuf field <code>string workflow_id = 2;</code>
     * @return string
     */
    public function getWorkflowId()
    {
        return $this->workflow_id;
    }

    /**
     * Can never be empty
     *
     * Generated from protobuf field <code>string workflow_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkflowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->workflow_id = $var;

        return $this;
    }

    /**
     * May be empty if the most recent run of the workflow with the given ID is being targeted
     *
     * Generated from protobuf field <code>string run_id = 3;</code>
     * @return string
     */
    public function getRunId()
    {
        return $this->run_id;
    }

    /**
     * May be empty if the most recent run of the workflow with the given ID is being targeted
     *
     * Generated from protobuf field <code>string run_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRunId($var)
    {
        GPBUtil::checkString($var, True);
        $this->run_id = $var;

        return $this;
    }

}

