<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/common/common.proto

namespace Coresdk\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>coresdk.common.WorkerDeploymentVersion</code>
 */
class WorkerDeploymentVersion extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string deployment_name = 1;</code>
     */
    protected $deployment_name = '';
    /**
     * Generated from protobuf field <code>string build_id = 2;</code>
     */
    protected $build_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $deployment_name
     *     @type string $build_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\Common\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string deployment_name = 1;</code>
     * @return string
     */
    public function getDeploymentName()
    {
        return $this->deployment_name;
    }

    /**
     * Generated from protobuf field <code>string deployment_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeploymentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->deployment_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string build_id = 2;</code>
     * @return string
     */
    public function getBuildId()
    {
        return $this->build_id;
    }

    /**
     * Generated from protobuf field <code>string build_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBuildId($var)
    {
        GPBUtil::checkString($var, True);
        $this->build_id = $var;

        return $this;
    }

}

