<?php

declare(strict_types=1);

/**
 * Generates the coresdk protobuf PHP classes used by the TrueAsync worker.
 *
 * These are the bridge types exchanged with the Temporal Rust core
 * (sdk-core-c-bridge): the activity task we poll and the completion we send
 * back. They are NOT part of temporal.api.* (those ship via the
 * roadrunner-php/roadrunner-api-dto package) — the generated classes here
 * reference the existing Temporal\Api\* classes rather than duplicating them.
 *
 * The .proto sources live in the Rust core checkout (the php-temporal C
 * extension vendors it as a submodule). Point TEMPORAL_SDK_RUST_PROTOS at its
 * `crates/common/protos` directory, or keep php-temporal as a sibling of this
 * repo (the default below).
 *
 * Output namespaces:
 *   Coresdk\*                        -> bridge/Coresdk
 *   GPBMetadata\Temporal\Sdk\Core\*  -> bridge/GPBMetadata/Temporal/Sdk/Core
 */

$root = dirname(__DIR__, 2);

$protosRoot = getenv('TEMPORAL_SDK_RUST_PROTOS')
    ?: $root . '/../php-temporal/third_party/sdk-rust/crates/common/protos';

$local = $protosRoot . '/local';
$apiUpstream = $protosRoot . '/api_upstream';

if (!is_dir($local) || !is_dir($apiUpstream)) {
    fwrite(STDERR, "Cannot find Rust core protos under: {$protosRoot}\n");
    fwrite(STDERR, "Set TEMPORAL_SDK_RUST_PROTOS to <sdk-rust>/crates/common/protos.\n");
    exit(1);
}

/* The full coresdk surface: the activity worker (activity_task/result and
   core_interface's ActivityTaskCompletion / ActivityHeartbeat) and the workflow
   worker (workflow_activation / commands / completion). core_interface.proto
   eagerly initializes its entire import closure, so the whole tree is generated.
   The temporal.api.* imports resolve to the Temporal\Api\* classes generated by
   generate-api-proto.php from the same Rust core protos, so there is no version
   skew. */
$files = [
    'temporal/sdk/core/common/common.proto',
    'temporal/sdk/core/external_data/external_data.proto',
    'temporal/sdk/core/activity_task/activity_task.proto',
    'temporal/sdk/core/activity_result/activity_result.proto',
    'temporal/sdk/core/child_workflow/child_workflow.proto',
    'temporal/sdk/core/nexus/nexus.proto',
    'temporal/sdk/core/workflow_activation/workflow_activation.proto',
    'temporal/sdk/core/workflow_commands/workflow_commands.proto',
    'temporal/sdk/core/workflow_completion/workflow_completion.proto',
    'temporal/sdk/core/core_interface.proto',
];

$out = $root . '/bridge';
if (!is_dir($out) && !mkdir($out, 0777, true) && !is_dir($out)) {
    fwrite(STDERR, "Cannot create output dir: {$out}\n");
    exit(1);
}

$cmd = array_merge(
    ['protoc', '-I', $local, '-I', $apiUpstream, '--php_out=' . $out],
    $files
);

$escaped = implode(' ', array_map('escapeshellarg', $cmd));
echo $escaped, "\n";

passthru($escaped, $code);
exit($code);
