<?php

declare(strict_types=1);

/**
 * Generates the temporal.api.* protobuf PHP classes the SDK speaks to the
 * Temporal frontend with (Temporal\Api\*), from the Rust core's vendored
 * protos. This replaces the third-party roadrunner-php/roadrunner-api-dto
 * package so that the api classes are version-locked to the exact core
 * (sdk-core-c-bridge) we link, and stay consistent with the coresdk bridge
 * classes generated by generate-coresdk-proto.php.
 *
 * Point TEMPORAL_SDK_RUST_PROTOS at <sdk-rust>/crates/common/protos, or keep
 * php-temporal as a sibling checkout (the default below).
 *
 * Output namespaces:
 *   Temporal\Api\*                 -> api/Temporal/Api
 *   GPBMetadata\Temporal\Api\*     -> api/GPBMetadata/Temporal/Api
 *
 * The google.api.* / google.protobuf.* imports resolve to the google/protobuf
 * runtime and the google/common-protos package (both already required), so they
 * are not generated here. The gRPC service.proto files are skipped: the SDK
 * talks through ServiceClientInterface, not generated stubs; the request/
 * response messages live in request_response.proto.
 */

$root = dirname(__DIR__, 2);

$protosRoot = getenv('TEMPORAL_SDK_RUST_PROTOS')
    ?: $root . '/../php-temporal/third_party/sdk-rust/crates/common/protos';

$apiUpstream = $protosRoot . '/api_upstream';

if (!is_dir($apiUpstream)) {
    fwrite(STDERR, "Cannot find Rust core protos under: {$protosRoot}\n");
    fwrite(STDERR, "Set TEMPORAL_SDK_RUST_PROTOS to <sdk-rust>/crates/common/protos.\n");
    exit(1);
}

/* Every temporal/api message proto, minus the pure-gRPC service definitions. */
$files = [];
$it = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($apiUpstream . '/temporal/api', FilesystemIterator::SKIP_DOTS),
);
foreach ($it as $f) {
    if ($f->getExtension() !== 'proto' || $f->getFilename() === 'service.proto') {
        continue;
    }
    $files[] = substr($f->getPathname(), strlen($apiUpstream) + 1);
}
sort($files);

$out = $root . '/api';
if (!is_dir($out) && !mkdir($out, 0777, true) && !is_dir($out)) {
    fwrite(STDERR, "Cannot create output dir: {$out}\n");
    exit(1);
}

$cmd = array_merge(['protoc', '-I', $apiUpstream, '--php_out=' . $out], $files);

echo 'protoc -I ' . $apiUpstream . " --php_out={$out} (" . count($files) . " files)\n";

passthru(implode(' ', array_map('escapeshellarg', $cmd)), $code);
exit($code);
