<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/external_data/external_data.proto

namespace GPBMetadata\Temporal\Sdk\Core\ExternalData;

class ExternalData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
ß
3temporal/sdk/core/external_data/external_data.protocoresdk.external_datagoogle/protobuf/timestamp.proto"þ
LocalActivityMarkerData
seq (
attempt (
activity_id (	
activity_type (	1
complete_time (2.google.protobuf.Timestamp*
backoff (2.google.protobuf.Duration:
original_schedule_time (2.google.protobuf.Timestamp"3
PatchedMarkerData

id (	

deprecated (B2ê/Temporalio::Internal::Bridge::Api::ExternalDatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

