<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/sdk/v1/external_storage.proto

namespace GPBMetadata\Temporal\Api\Sdk\V1;

class ExternalStorage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
„
*temporal/api/sdk/v1/external_storage.prototemporal.api.sdk.v1"³
ExternalStorageReference
driver_name (	P

claim_data (2<.temporal.api.sdk.v1.ExternalStorageReference.ClaimDataEntry0
ClaimDataEntry
key (	
value (	:8B‚
io.temporal.api.sdk.v1BExternalStorageProtoPZgo.temporal.io/api/sdk/v1;sdkªTemporalio.Api.Sdk.V1êTemporalio::Api::Sdk::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

