<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/activity/v1/message.proto

namespace Temporal\Api\Activity\V1;

if (false) {
    /**
     * This class is deprecated. Use Temporal\Api\Activity\V1\CallbackInfo\Trigger instead.
     * @deprecated
     */
    class CallbackInfo_Trigger {}
}
class_exists(CallbackInfo\Trigger::class);
@trigger_error('Temporal\Api\Activity\V1\CallbackInfo_Trigger is deprecated and will be removed in the next major release. Use Temporal\Api\Activity\V1\CallbackInfo\Trigger instead', E_USER_DEPRECATED);

