<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/activity/v1/message.proto

namespace Temporal\Api\Activity\V1;

if (false) {
    /**
     * This class is deprecated. Use Temporal\Api\Activity\V1\CallbackInfo\ActivityClosed instead.
     * @deprecated
     */
    class CallbackInfo_ActivityClosed {}
}
class_exists(CallbackInfo\ActivityClosed::class);
@trigger_error('Temporal\Api\Activity\V1\CallbackInfo_ActivityClosed is deprecated and will be removed in the next major release. Use Temporal\Api\Activity\V1\CallbackInfo\ActivityClosed instead', E_USER_DEPRECATED);

