<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/activity/v1/message.proto

namespace Temporal\Api\Activity\V1\CallbackInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Trigger for when the activity is closed.
 *
 * Generated from protobuf message <code>temporal.api.activity.v1.CallbackInfo.ActivityClosed</code>
 */
class ActivityClosed extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Activity\V1\Message::initOnce();
        parent::__construct($data);
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ActivityClosed::class, \Temporal\Api\Activity\V1\CallbackInfo_ActivityClosed::class);

