<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/activity/v1/message.proto

namespace Temporal\Api\Activity\V1\CallbackInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.activity.v1.CallbackInfo.Trigger</code>
 */
class Trigger extends \Google\Protobuf\Internal\Message
{
    protected $variant;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Temporal\Api\Activity\V1\CallbackInfo\ActivityClosed $activity_closed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Activity\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.activity.v1.CallbackInfo.ActivityClosed activity_closed = 1;</code>
     * @return \Temporal\Api\Activity\V1\CallbackInfo\ActivityClosed|null
     */
    public function getActivityClosed()
    {
        return $this->readOneof(1);
    }

    public function hasActivityClosed()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.activity.v1.CallbackInfo.ActivityClosed activity_closed = 1;</code>
     * @param \Temporal\Api\Activity\V1\CallbackInfo\ActivityClosed $var
     * @return $this
     */
    public function setActivityClosed($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Activity\V1\CallbackInfo\ActivityClosed::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVariant()
    {
        return $this->whichOneof("variant");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Trigger::class, \Temporal\Api\Activity\V1\CallbackInfo_Trigger::class);

