<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Initialize a new workflow
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.InitializeWorkflow</code>
 */
class InitializeWorkflow extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifier the lang-specific sdk uses to execute workflow code
     *
     * Generated from protobuf field <code>string workflow_type = 1;</code>
     */
    protected $workflow_type = '';
    /**
     * The workflow id used on the temporal server
     *
     * Generated from protobuf field <code>string workflow_id = 2;</code>
     */
    protected $workflow_id = '';
    /**
     * Inputs to the workflow code
     *
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload arguments = 3;</code>
     */
    private $arguments;
    /**
     * The seed must be used to initialize the random generator used by SDK.
     * RandomSeedUpdatedAttributes are used to deliver seed updates.
     *
     * Generated from protobuf field <code>uint64 randomness_seed = 4;</code>
     */
    protected $randomness_seed = 0;
    /**
     * Used to add metadata e.g. for tracing and auth, meant to be read and written to by interceptors.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 5;</code>
     */
    private $headers;
    /**
     * Identity of the client who requested this execution
     *
     * Generated from protobuf field <code>string identity = 6;</code>
     */
    protected $identity = '';
    /**
     * If this workflow is a child, information about the parent
     *
     * Generated from protobuf field <code>.coresdk.common.NamespacedWorkflowExecution parent_workflow_info = 7;</code>
     */
    protected $parent_workflow_info = null;
    /**
     * Total workflow execution timeout including retries and continue as new.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_execution_timeout = 8;</code>
     */
    protected $workflow_execution_timeout = null;
    /**
     * Timeout of a single workflow run.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_run_timeout = 9;</code>
     */
    protected $workflow_run_timeout = null;
    /**
     * Timeout of a single workflow task.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_task_timeout = 10;</code>
     */
    protected $workflow_task_timeout = null;
    /**
     * Run id of the previous workflow which continued-as-new or retired or cron executed into this
     * workflow, if any.
     *
     * Generated from protobuf field <code>string continued_from_execution_run_id = 11;</code>
     */
    protected $continued_from_execution_run_id = '';
    /**
     * If this workflow was a continuation, indicates the type of continuation.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.ContinueAsNewInitiator continued_initiator = 12;</code>
     */
    protected $continued_initiator = 0;
    /**
     * If this workflow was a continuation and that continuation failed, the details of that.
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure continued_failure = 13;</code>
     */
    protected $continued_failure = null;
    /**
     * If this workflow was a continuation and that continuation completed, the details of that.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads last_completion_result = 14;</code>
     */
    protected $last_completion_result = null;
    /**
     * This is the very first run id the workflow ever had, following continuation chains.
     *
     * Generated from protobuf field <code>string first_execution_run_id = 15;</code>
     */
    protected $first_execution_run_id = '';
    /**
     * This workflow's retry policy
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.RetryPolicy retry_policy = 16;</code>
     */
    protected $retry_policy = null;
    /**
     * Starting at 1, the number of times we have tried to execute this workflow
     *
     * Generated from protobuf field <code>int32 attempt = 17;</code>
     */
    protected $attempt = 0;
    /**
     * If this workflow runs on a cron schedule, it will appear here
     *
     * Generated from protobuf field <code>string cron_schedule = 18;</code>
     */
    protected $cron_schedule = '';
    /**
     * The absolute time at which the workflow will be timed out.
     * This is passed without change to the next run/retry of a workflow.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp workflow_execution_expiration_time = 19;</code>
     */
    protected $workflow_execution_expiration_time = null;
    /**
     * For a cron workflow, this contains the amount of time between when this iteration of
     * the cron workflow was scheduled and when it should run next per its cron_schedule.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration cron_schedule_to_schedule_interval = 20;</code>
     */
    protected $cron_schedule_to_schedule_interval = null;
    /**
     * User-defined memo
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Memo memo = 21;</code>
     */
    protected $memo = null;
    /**
     * Search attributes created/updated when this workflow was started
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.SearchAttributes search_attributes = 22;</code>
     */
    protected $search_attributes = null;
    /**
     * When the workflow execution started event was first written
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 23;</code>
     */
    protected $start_time = null;
    /**
     * Contains information about the root workflow execution. It is possible for the namespace to
     * be different than this workflow if using OSS and cross-namespace children, but this
     * information is not retained. Users should take care to track it by other means in such
     * situations.
     * The root workflow execution is defined as follows:
     *   1. A workflow without parent workflow is its own root workflow.
     *   2. A workflow that has a parent workflow has the same root workflow as its parent workflow.
     * See field in WorkflowExecutionStarted for more detail.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowExecution root_workflow = 24;</code>
     */
    protected $root_workflow = null;
    /**
     * Priority of this workflow execution
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Priority priority = 25;</code>
     */
    protected $priority = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $workflow_type
     *           The identifier the lang-specific sdk uses to execute workflow code
     *     @type string $workflow_id
     *           The workflow id used on the temporal server
     *     @type array<\Temporal\Api\Common\V1\Payload>|\Google\Protobuf\Internal\RepeatedField $arguments
     *           Inputs to the workflow code
     *     @type int|string $randomness_seed
     *           The seed must be used to initialize the random generator used by SDK.
     *           RandomSeedUpdatedAttributes are used to deliver seed updates.
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     *           Used to add metadata e.g. for tracing and auth, meant to be read and written to by interceptors.
     *     @type string $identity
     *           Identity of the client who requested this execution
     *     @type \Coresdk\Common\NamespacedWorkflowExecution $parent_workflow_info
     *           If this workflow is a child, information about the parent
     *     @type \Google\Protobuf\Duration $workflow_execution_timeout
     *           Total workflow execution timeout including retries and continue as new.
     *     @type \Google\Protobuf\Duration $workflow_run_timeout
     *           Timeout of a single workflow run.
     *     @type \Google\Protobuf\Duration $workflow_task_timeout
     *           Timeout of a single workflow task.
     *     @type string $continued_from_execution_run_id
     *           Run id of the previous workflow which continued-as-new or retired or cron executed into this
     *           workflow, if any.
     *     @type int $continued_initiator
     *           If this workflow was a continuation, indicates the type of continuation.
     *     @type \Temporal\Api\Failure\V1\Failure $continued_failure
     *           If this workflow was a continuation and that continuation failed, the details of that.
     *     @type \Temporal\Api\Common\V1\Payloads $last_completion_result
     *           If this workflow was a continuation and that continuation completed, the details of that.
     *     @type string $first_execution_run_id
     *           This is the very first run id the workflow ever had, following continuation chains.
     *     @type \Temporal\Api\Common\V1\RetryPolicy $retry_policy
     *           This workflow's retry policy
     *     @type int $attempt
     *           Starting at 1, the number of times we have tried to execute this workflow
     *     @type string $cron_schedule
     *           If this workflow runs on a cron schedule, it will appear here
     *     @type \Google\Protobuf\Timestamp $workflow_execution_expiration_time
     *           The absolute time at which the workflow will be timed out.
     *           This is passed without change to the next run/retry of a workflow.
     *     @type \Google\Protobuf\Duration $cron_schedule_to_schedule_interval
     *           For a cron workflow, this contains the amount of time between when this iteration of
     *           the cron workflow was scheduled and when it should run next per its cron_schedule.
     *     @type \Temporal\Api\Common\V1\Memo $memo
     *           User-defined memo
     *     @type \Temporal\Api\Common\V1\SearchAttributes $search_attributes
     *           Search attributes created/updated when this workflow was started
     *     @type \Google\Protobuf\Timestamp $start_time
     *           When the workflow execution started event was first written
     *     @type \Temporal\Api\Common\V1\WorkflowExecution $root_workflow
     *           Contains information about the root workflow execution. It is possible for the namespace to
     *           be different than this workflow if using OSS and cross-namespace children, but this
     *           information is not retained. Users should take care to track it by other means in such
     *           situations.
     *           The root workflow execution is defined as follows:
     *             1. A workflow without parent workflow is its own root workflow.
     *             2. A workflow that has a parent workflow has the same root workflow as its parent workflow.
     *           See field in WorkflowExecutionStarted for more detail.
     *     @type \Temporal\Api\Common\V1\Priority $priority
     *           Priority of this workflow execution
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifier the lang-specific sdk uses to execute workflow code
     *
     * Generated from protobuf field <code>string workflow_type = 1;</code>
     * @return string
     */
    public function getWorkflowType()
    {
        return $this->workflow_type;
    }

    /**
     * The identifier the lang-specific sdk uses to execute workflow code
     *
     * Generated from protobuf field <code>string workflow_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkflowType($var)
    {
        GPBUtil::checkString($var, True);
        $this->workflow_type = $var;

        return $this;
    }

    /**
     * The workflow id used on the temporal server
     *
     * Generated from protobuf field <code>string workflow_id = 2;</code>
     * @return string
     */
    public function getWorkflowId()
    {
        return $this->workflow_id;
    }

    /**
     * The workflow id used on the temporal server
     *
     * Generated from protobuf field <code>string workflow_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkflowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->workflow_id = $var;

        return $this;
    }

    /**
     * Inputs to the workflow code
     *
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload arguments = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArguments()
    {
        return $this->arguments;
    }

    /**
     * Inputs to the workflow code
     *
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload arguments = 3;</code>
     * @param array<\Temporal\Api\Common\V1\Payload>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArguments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Common\V1\Payload::class);
        $this->arguments = $arr;

        return $this;
    }

    /**
     * The seed must be used to initialize the random generator used by SDK.
     * RandomSeedUpdatedAttributes are used to deliver seed updates.
     *
     * Generated from protobuf field <code>uint64 randomness_seed = 4;</code>
     * @return int|string
     */
    public function getRandomnessSeed()
    {
        return $this->randomness_seed;
    }

    /**
     * The seed must be used to initialize the random generator used by SDK.
     * RandomSeedUpdatedAttributes are used to deliver seed updates.
     *
     * Generated from protobuf field <code>uint64 randomness_seed = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRandomnessSeed($var)
    {
        GPBUtil::checkUint64($var);
        $this->randomness_seed = $var;

        return $this;
    }

    /**
     * Used to add metadata e.g. for tracing and auth, meant to be read and written to by interceptors.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Used to add metadata e.g. for tracing and auth, meant to be read and written to by interceptors.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Common\V1\Payload::class);
        $this->headers = $arr;

        return $this;
    }

    /**
     * Identity of the client who requested this execution
     *
     * Generated from protobuf field <code>string identity = 6;</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Identity of the client who requested this execution
     *
     * Generated from protobuf field <code>string identity = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity = $var;

        return $this;
    }

    /**
     * If this workflow is a child, information about the parent
     *
     * Generated from protobuf field <code>.coresdk.common.NamespacedWorkflowExecution parent_workflow_info = 7;</code>
     * @return \Coresdk\Common\NamespacedWorkflowExecution|null
     */
    public function getParentWorkflowInfo()
    {
        return $this->parent_workflow_info;
    }

    public function hasParentWorkflowInfo()
    {
        return isset($this->parent_workflow_info);
    }

    public function clearParentWorkflowInfo()
    {
        unset($this->parent_workflow_info);
    }

    /**
     * If this workflow is a child, information about the parent
     *
     * Generated from protobuf field <code>.coresdk.common.NamespacedWorkflowExecution parent_workflow_info = 7;</code>
     * @param \Coresdk\Common\NamespacedWorkflowExecution $var
     * @return $this
     */
    public function setParentWorkflowInfo($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\Common\NamespacedWorkflowExecution::class);
        $this->parent_workflow_info = $var;

        return $this;
    }

    /**
     * Total workflow execution timeout including retries and continue as new.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_execution_timeout = 8;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getWorkflowExecutionTimeout()
    {
        return $this->workflow_execution_timeout;
    }

    public function hasWorkflowExecutionTimeout()
    {
        return isset($this->workflow_execution_timeout);
    }

    public function clearWorkflowExecutionTimeout()
    {
        unset($this->workflow_execution_timeout);
    }

    /**
     * Total workflow execution timeout including retries and continue as new.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_execution_timeout = 8;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setWorkflowExecutionTimeout($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->workflow_execution_timeout = $var;

        return $this;
    }

    /**
     * Timeout of a single workflow run.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_run_timeout = 9;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getWorkflowRunTimeout()
    {
        return $this->workflow_run_timeout;
    }

    public function hasWorkflowRunTimeout()
    {
        return isset($this->workflow_run_timeout);
    }

    public function clearWorkflowRunTimeout()
    {
        unset($this->workflow_run_timeout);
    }

    /**
     * Timeout of a single workflow run.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_run_timeout = 9;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setWorkflowRunTimeout($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->workflow_run_timeout = $var;

        return $this;
    }

    /**
     * Timeout of a single workflow task.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_task_timeout = 10;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getWorkflowTaskTimeout()
    {
        return $this->workflow_task_timeout;
    }

    public function hasWorkflowTaskTimeout()
    {
        return isset($this->workflow_task_timeout);
    }

    public function clearWorkflowTaskTimeout()
    {
        unset($this->workflow_task_timeout);
    }

    /**
     * Timeout of a single workflow task.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_task_timeout = 10;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setWorkflowTaskTimeout($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->workflow_task_timeout = $var;

        return $this;
    }

    /**
     * Run id of the previous workflow which continued-as-new or retired or cron executed into this
     * workflow, if any.
     *
     * Generated from protobuf field <code>string continued_from_execution_run_id = 11;</code>
     * @return string
     */
    public function getContinuedFromExecutionRunId()
    {
        return $this->continued_from_execution_run_id;
    }

    /**
     * Run id of the previous workflow which continued-as-new or retired or cron executed into this
     * workflow, if any.
     *
     * Generated from protobuf field <code>string continued_from_execution_run_id = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setContinuedFromExecutionRunId($var)
    {
        GPBUtil::checkString($var, True);
        $this->continued_from_execution_run_id = $var;

        return $this;
    }

    /**
     * If this workflow was a continuation, indicates the type of continuation.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.ContinueAsNewInitiator continued_initiator = 12;</code>
     * @return int
     */
    public function getContinuedInitiator()
    {
        return $this->continued_initiator;
    }

    /**
     * If this workflow was a continuation, indicates the type of continuation.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.ContinueAsNewInitiator continued_initiator = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setContinuedInitiator($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\ContinueAsNewInitiator::class);
        $this->continued_initiator = $var;

        return $this;
    }

    /**
     * If this workflow was a continuation and that continuation failed, the details of that.
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure continued_failure = 13;</code>
     * @return \Temporal\Api\Failure\V1\Failure|null
     */
    public function getContinuedFailure()
    {
        return $this->continued_failure;
    }

    public function hasContinuedFailure()
    {
        return isset($this->continued_failure);
    }

    public function clearContinuedFailure()
    {
        unset($this->continued_failure);
    }

    /**
     * If this workflow was a continuation and that continuation failed, the details of that.
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure continued_failure = 13;</code>
     * @param \Temporal\Api\Failure\V1\Failure $var
     * @return $this
     */
    public function setContinuedFailure($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Failure\V1\Failure::class);
        $this->continued_failure = $var;

        return $this;
    }

    /**
     * If this workflow was a continuation and that continuation completed, the details of that.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads last_completion_result = 14;</code>
     * @return \Temporal\Api\Common\V1\Payloads|null
     */
    public function getLastCompletionResult()
    {
        return $this->last_completion_result;
    }

    public function hasLastCompletionResult()
    {
        return isset($this->last_completion_result);
    }

    public function clearLastCompletionResult()
    {
        unset($this->last_completion_result);
    }

    /**
     * If this workflow was a continuation and that continuation completed, the details of that.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads last_completion_result = 14;</code>
     * @param \Temporal\Api\Common\V1\Payloads $var
     * @return $this
     */
    public function setLastCompletionResult($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\Payloads::class);
        $this->last_completion_result = $var;

        return $this;
    }

    /**
     * This is the very first run id the workflow ever had, following continuation chains.
     *
     * Generated from protobuf field <code>string first_execution_run_id = 15;</code>
     * @return string
     */
    public function getFirstExecutionRunId()
    {
        return $this->first_execution_run_id;
    }

    /**
     * This is the very first run id the workflow ever had, following continuation chains.
     *
     * Generated from protobuf field <code>string first_execution_run_id = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstExecutionRunId($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_execution_run_id = $var;

        return $this;
    }

    /**
     * This workflow's retry policy
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.RetryPolicy retry_policy = 16;</code>
     * @return \Temporal\Api\Common\V1\RetryPolicy|null
     */
    public function getRetryPolicy()
    {
        return $this->retry_policy;
    }

    public function hasRetryPolicy()
    {
        return isset($this->retry_policy);
    }

    public function clearRetryPolicy()
    {
        unset($this->retry_policy);
    }

    /**
     * This workflow's retry policy
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.RetryPolicy retry_policy = 16;</code>
     * @param \Temporal\Api\Common\V1\RetryPolicy $var
     * @return $this
     */
    public function setRetryPolicy($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\RetryPolicy::class);
        $this->retry_policy = $var;

        return $this;
    }

    /**
     * Starting at 1, the number of times we have tried to execute this workflow
     *
     * Generated from protobuf field <code>int32 attempt = 17;</code>
     * @return int
     */
    public function getAttempt()
    {
        return $this->attempt;
    }

    /**
     * Starting at 1, the number of times we have tried to execute this workflow
     *
     * Generated from protobuf field <code>int32 attempt = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setAttempt($var)
    {
        GPBUtil::checkInt32($var);
        $this->attempt = $var;

        return $this;
    }

    /**
     * If this workflow runs on a cron schedule, it will appear here
     *
     * Generated from protobuf field <code>string cron_schedule = 18;</code>
     * @return string
     */
    public function getCronSchedule()
    {
        return $this->cron_schedule;
    }

    /**
     * If this workflow runs on a cron schedule, it will appear here
     *
     * Generated from protobuf field <code>string cron_schedule = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setCronSchedule($var)
    {
        GPBUtil::checkString($var, True);
        $this->cron_schedule = $var;

        return $this;
    }

    /**
     * The absolute time at which the workflow will be timed out.
     * This is passed without change to the next run/retry of a workflow.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp workflow_execution_expiration_time = 19;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getWorkflowExecutionExpirationTime()
    {
        return $this->workflow_execution_expiration_time;
    }

    public function hasWorkflowExecutionExpirationTime()
    {
        return isset($this->workflow_execution_expiration_time);
    }

    public function clearWorkflowExecutionExpirationTime()
    {
        unset($this->workflow_execution_expiration_time);
    }

    /**
     * The absolute time at which the workflow will be timed out.
     * This is passed without change to the next run/retry of a workflow.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp workflow_execution_expiration_time = 19;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setWorkflowExecutionExpirationTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->workflow_execution_expiration_time = $var;

        return $this;
    }

    /**
     * For a cron workflow, this contains the amount of time between when this iteration of
     * the cron workflow was scheduled and when it should run next per its cron_schedule.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration cron_schedule_to_schedule_interval = 20;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getCronScheduleToScheduleInterval()
    {
        return $this->cron_schedule_to_schedule_interval;
    }

    public function hasCronScheduleToScheduleInterval()
    {
        return isset($this->cron_schedule_to_schedule_interval);
    }

    public function clearCronScheduleToScheduleInterval()
    {
        unset($this->cron_schedule_to_schedule_interval);
    }

    /**
     * For a cron workflow, this contains the amount of time between when this iteration of
     * the cron workflow was scheduled and when it should run next per its cron_schedule.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration cron_schedule_to_schedule_interval = 20;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setCronScheduleToScheduleInterval($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->cron_schedule_to_schedule_interval = $var;

        return $this;
    }

    /**
     * User-defined memo
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Memo memo = 21;</code>
     * @return \Temporal\Api\Common\V1\Memo|null
     */
    public function getMemo()
    {
        return $this->memo;
    }

    public function hasMemo()
    {
        return isset($this->memo);
    }

    public function clearMemo()
    {
        unset($this->memo);
    }

    /**
     * User-defined memo
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Memo memo = 21;</code>
     * @param \Temporal\Api\Common\V1\Memo $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\Memo::class);
        $this->memo = $var;

        return $this;
    }

    /**
     * Search attributes created/updated when this workflow was started
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.SearchAttributes search_attributes = 22;</code>
     * @return \Temporal\Api\Common\V1\SearchAttributes|null
     */
    public function getSearchAttributes()
    {
        return $this->search_attributes;
    }

    public function hasSearchAttributes()
    {
        return isset($this->search_attributes);
    }

    public function clearSearchAttributes()
    {
        unset($this->search_attributes);
    }

    /**
     * Search attributes created/updated when this workflow was started
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.SearchAttributes search_attributes = 22;</code>
     * @param \Temporal\Api\Common\V1\SearchAttributes $var
     * @return $this
     */
    public function setSearchAttributes($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\SearchAttributes::class);
        $this->search_attributes = $var;

        return $this;
    }

    /**
     * When the workflow execution started event was first written
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 23;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * When the workflow execution started event was first written
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 23;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Contains information about the root workflow execution. It is possible for the namespace to
     * be different than this workflow if using OSS and cross-namespace children, but this
     * information is not retained. Users should take care to track it by other means in such
     * situations.
     * The root workflow execution is defined as follows:
     *   1. A workflow without parent workflow is its own root workflow.
     *   2. A workflow that has a parent workflow has the same root workflow as its parent workflow.
     * See field in WorkflowExecutionStarted for more detail.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowExecution root_workflow = 24;</code>
     * @return \Temporal\Api\Common\V1\WorkflowExecution|null
     */
    public function getRootWorkflow()
    {
        return $this->root_workflow;
    }

    public function hasRootWorkflow()
    {
        return isset($this->root_workflow);
    }

    public function clearRootWorkflow()
    {
        unset($this->root_workflow);
    }

    /**
     * Contains information about the root workflow execution. It is possible for the namespace to
     * be different than this workflow if using OSS and cross-namespace children, but this
     * information is not retained. Users should take care to track it by other means in such
     * situations.
     * The root workflow execution is defined as follows:
     *   1. A workflow without parent workflow is its own root workflow.
     *   2. A workflow that has a parent workflow has the same root workflow as its parent workflow.
     * See field in WorkflowExecutionStarted for more detail.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowExecution root_workflow = 24;</code>
     * @param \Temporal\Api\Common\V1\WorkflowExecution $var
     * @return $this
     */
    public function setRootWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\WorkflowExecution::class);
        $this->root_workflow = $var;

        return $this;
    }

    /**
     * Priority of this workflow execution
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Priority priority = 25;</code>
     * @return \Temporal\Api\Common\V1\Priority|null
     */
    public function getPriority()
    {
        return $this->priority;
    }

    public function hasPriority()
    {
        return isset($this->priority);
    }

    public function clearPriority()
    {
        unset($this->priority);
    }

    /**
     * Priority of this workflow execution
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Priority priority = 25;</code>
     * @param \Temporal\Api\Common\V1\Priority $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\Priority::class);
        $this->priority = $var;

        return $this;
    }

}

