<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Inform lang what the result of a call to `patched` or similar API should be -- this is always
 * sent pre-emptively, so any time it is sent the change is present
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.NotifyHasPatch</code>
 */
class NotifyHasPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string patch_id = 1;</code>
     */
    protected $patch_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $patch_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string patch_id = 1;</code>
     * @return string
     */
    public function getPatchId()
    {
        return $this->patch_id;
    }

    /**
     * Generated from protobuf field <code>string patch_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPatchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->patch_id = $var;

        return $this;
    }

}

