<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>coresdk.workflow_activation.ResolveRequestCancelExternalWorkflow</code>
 */
class ResolveRequestCancelExternalWorkflow extends \Google\Protobuf\Internal\Message
{
    /**
     * Sequence number as provided by lang in the corresponding
     * RequestCancelExternalWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     */
    protected $seq = 0;
    /**
     * If populated, this signal either failed to be sent or was cancelled depending on failure
     * type / info.
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 2;</code>
     */
    protected $failure = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seq
     *           Sequence number as provided by lang in the corresponding
     *           RequestCancelExternalWorkflowExecution command
     *     @type \Temporal\Api\Failure\V1\Failure $failure
     *           If populated, this signal either failed to be sent or was cancelled depending on failure
     *           type / info.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * Sequence number as provided by lang in the corresponding
     * RequestCancelExternalWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Sequence number as provided by lang in the corresponding
     * RequestCancelExternalWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * If populated, this signal either failed to be sent or was cancelled depending on failure
     * type / info.
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 2;</code>
     * @return \Temporal\Api\Failure\V1\Failure|null
     */
    public function getFailure()
    {
        return $this->failure;
    }

    public function hasFailure()
    {
        return isset($this->failure);
    }

    public function clearFailure()
    {
        unset($this->failure);
    }

    /**
     * If populated, this signal either failed to be sent or was cancelled depending on failure
     * type / info.
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 2;</code>
     * @param \Temporal\Api\Failure\V1\Failure $var
     * @return $this
     */
    public function setFailure($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Failure\V1\Failure::class);
        $this->failure = $var;

        return $this;
    }

}

