<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Notify a workflow that a child workflow execution has been resolved
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.ResolveChildWorkflowExecution</code>
 */
class ResolveChildWorkflowExecution extends \Google\Protobuf\Internal\Message
{
    /**
     * Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     */
    protected $seq = 0;
    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.ChildWorkflowResult result = 2;</code>
     */
    protected $result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seq
     *           Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *     @type \Coresdk\ChildWorkflow\ChildWorkflowResult $result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.ChildWorkflowResult result = 2;</code>
     * @return \Coresdk\ChildWorkflow\ChildWorkflowResult|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.ChildWorkflowResult result = 2;</code>
     * @param \Coresdk\ChildWorkflow\ChildWorkflowResult $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ChildWorkflow\ChildWorkflowResult::class);
        $this->result = $var;

        return $this;
    }

}

