<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Notify a workflow that an activity has been resolved
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.ResolveActivity</code>
 */
class ResolveActivity extends \Google\Protobuf\Internal\Message
{
    /**
     * Sequence number as provided by lang in the corresponding ScheduleActivity command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     */
    protected $seq = 0;
    /**
     * Generated from protobuf field <code>.coresdk.activity_result.ActivityResolution result = 2;</code>
     */
    protected $result = null;
    /**
     * Set to true if the resolution is for a local activity. This is used internally by Core and
     * lang does not need to care about it.
     *
     * Generated from protobuf field <code>bool is_local = 3;</code>
     */
    protected $is_local = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seq
     *           Sequence number as provided by lang in the corresponding ScheduleActivity command
     *     @type \Coresdk\ActivityResult\ActivityResolution $result
     *     @type bool $is_local
     *           Set to true if the resolution is for a local activity. This is used internally by Core and
     *           lang does not need to care about it.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * Sequence number as provided by lang in the corresponding ScheduleActivity command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Sequence number as provided by lang in the corresponding ScheduleActivity command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.ActivityResolution result = 2;</code>
     * @return \Coresdk\ActivityResult\ActivityResolution|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.ActivityResolution result = 2;</code>
     * @param \Coresdk\ActivityResult\ActivityResolution $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityResult\ActivityResolution::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Set to true if the resolution is for a local activity. This is used internally by Core and
     * lang does not need to care about it.
     *
     * Generated from protobuf field <code>bool is_local = 3;</code>
     * @return bool
     */
    public function getIsLocal()
    {
        return $this->is_local;
    }

    /**
     * Set to true if the resolution is for a local activity. This is used internally by Core and
     * lang does not need to care about it.
     *
     * Generated from protobuf field <code>bool is_local = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLocal($var)
    {
        GPBUtil::checkBool($var);
        $this->is_local = $var;

        return $this;
    }

}

