<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Notify a workflow that a start child workflow execution request has succeeded, failed or was
 * cancelled.
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.ResolveChildWorkflowExecutionStart</code>
 */
class ResolveChildWorkflowExecutionStart extends \Google\Protobuf\Internal\Message
{
    /**
     * Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     */
    protected $seq = 0;
    protected $status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seq
     *           Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *     @type \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartSuccess $succeeded
     *     @type \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartFailure $failed
     *     @type \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartCancelled $cancelled
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Sequence number as provided by lang in the corresponding StartChildWorkflowExecution command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStartSuccess succeeded = 2;</code>
     * @return \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartSuccess|null
     */
    public function getSucceeded()
    {
        return $this->readOneof(2);
    }

    public function hasSucceeded()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStartSuccess succeeded = 2;</code>
     * @param \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartSuccess $var
     * @return $this
     */
    public function setSucceeded($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartSuccess::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStartFailure failed = 3;</code>
     * @return \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartFailure|null
     */
    public function getFailed()
    {
        return $this->readOneof(3);
    }

    public function hasFailed()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStartFailure failed = 3;</code>
     * @param \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartFailure $var
     * @return $this
     */
    public function setFailed($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartFailure::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStartCancelled cancelled = 4;</code>
     * @return \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartCancelled|null
     */
    public function getCancelled()
    {
        return $this->readOneof(4);
    }

    public function hasCancelled()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStartCancelled cancelled = 4;</code>
     * @param \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartCancelled $var
     * @return $this
     */
    public function setCancelled($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStartCancelled::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->whichOneof("status");
    }

}

