<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Send a signal to a workflow
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.SignalWorkflow</code>
 */
class SignalWorkflow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string signal_name = 1;</code>
     */
    protected $signal_name = '';
    /**
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload input = 2;</code>
     */
    private $input;
    /**
     * Identity of the sender of the signal
     *
     * Generated from protobuf field <code>string identity = 3;</code>
     */
    protected $identity = '';
    /**
     * Headers attached to the signal
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 5;</code>
     */
    private $headers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signal_name
     *     @type array<\Temporal\Api\Common\V1\Payload>|\Google\Protobuf\Internal\RepeatedField $input
     *     @type string $identity
     *           Identity of the sender of the signal
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     *           Headers attached to the signal
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string signal_name = 1;</code>
     * @return string
     */
    public function getSignalName()
    {
        return $this->signal_name;
    }

    /**
     * Generated from protobuf field <code>string signal_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->signal_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload input = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload input = 2;</code>
     * @param array<\Temporal\Api\Common\V1\Payload>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInput($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Common\V1\Payload::class);
        $this->input = $arr;

        return $this;
    }

    /**
     * Identity of the sender of the signal
     *
     * Generated from protobuf field <code>string identity = 3;</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Identity of the sender of the signal
     *
     * Generated from protobuf field <code>string identity = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity = $var;

        return $this;
    }

    /**
     * Headers attached to the signal
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Headers attached to the signal
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Common\V1\Payload::class);
        $this->headers = $arr;

        return $this;
    }

}

