<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>coresdk.workflow_activation.WorkflowActivationJob</code>
 */
class WorkflowActivationJob extends \Google\Protobuf\Internal\Message
{
    protected $variant;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Coresdk\WorkflowActivation\InitializeWorkflow $initialize_workflow
     *           A workflow is starting, record all of the information from its start event
     *     @type \Coresdk\WorkflowActivation\FireTimer $fire_timer
     *           A timer has fired, allowing whatever was waiting on it (if anything) to proceed
     *     @type \Coresdk\WorkflowActivation\UpdateRandomSeed $update_random_seed
     *           Workflow was reset. The randomness seed must be updated.
     *     @type \Coresdk\WorkflowActivation\QueryWorkflow $query_workflow
     *           A request to query the workflow was received. It is guaranteed that queries (one or more)
     *           always come in their own activation after other mutating jobs.
     *     @type \Coresdk\WorkflowActivation\CancelWorkflow $cancel_workflow
     *           A request to cancel the workflow was received.
     *     @type \Coresdk\WorkflowActivation\SignalWorkflow $signal_workflow
     *           A request to signal the workflow was received.
     *     @type \Coresdk\WorkflowActivation\ResolveActivity $resolve_activity
     *           An activity was resolved, result could be completed, failed or cancelled
     *     @type \Coresdk\WorkflowActivation\NotifyHasPatch $notify_has_patch
     *           A patch marker has been detected and lang is being told that change exists. This
     *           job is strange in that it is sent pre-emptively to lang without any corresponding
     *           command being sent first.
     *     @type \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStart $resolve_child_workflow_execution_start
     *           A child workflow execution has started or failed to start
     *     @type \Coresdk\WorkflowActivation\ResolveChildWorkflowExecution $resolve_child_workflow_execution
     *           A child workflow was resolved, result could be completed or failed
     *     @type \Coresdk\WorkflowActivation\ResolveSignalExternalWorkflow $resolve_signal_external_workflow
     *           An attempt to signal an external workflow resolved
     *     @type \Coresdk\WorkflowActivation\ResolveRequestCancelExternalWorkflow $resolve_request_cancel_external_workflow
     *           An attempt to cancel an external workflow resolved
     *     @type \Coresdk\WorkflowActivation\DoUpdate $do_update
     *           A request to handle a workflow update.
     *     @type \Coresdk\WorkflowActivation\ResolveNexusOperationStart $resolve_nexus_operation_start
     *           A nexus operation started.
     *     @type \Coresdk\WorkflowActivation\ResolveNexusOperation $resolve_nexus_operation
     *           A nexus operation resolved.
     *     @type \Coresdk\WorkflowActivation\RemoveFromCache $remove_from_cache
     *           Remove the workflow identified by the [WorkflowActivation] containing this job from the
     *           cache after performing the activation. It is guaranteed that this will be the only job
     *           in the activation if present.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * A workflow is starting, record all of the information from its start event
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.InitializeWorkflow initialize_workflow = 1;</code>
     * @return \Coresdk\WorkflowActivation\InitializeWorkflow|null
     */
    public function getInitializeWorkflow()
    {
        return $this->readOneof(1);
    }

    public function hasInitializeWorkflow()
    {
        return $this->hasOneof(1);
    }

    /**
     * A workflow is starting, record all of the information from its start event
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.InitializeWorkflow initialize_workflow = 1;</code>
     * @param \Coresdk\WorkflowActivation\InitializeWorkflow $var
     * @return $this
     */
    public function setInitializeWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\InitializeWorkflow::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * A timer has fired, allowing whatever was waiting on it (if anything) to proceed
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.FireTimer fire_timer = 2;</code>
     * @return \Coresdk\WorkflowActivation\FireTimer|null
     */
    public function getFireTimer()
    {
        return $this->readOneof(2);
    }

    public function hasFireTimer()
    {
        return $this->hasOneof(2);
    }

    /**
     * A timer has fired, allowing whatever was waiting on it (if anything) to proceed
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.FireTimer fire_timer = 2;</code>
     * @param \Coresdk\WorkflowActivation\FireTimer $var
     * @return $this
     */
    public function setFireTimer($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\FireTimer::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Workflow was reset. The randomness seed must be updated.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.UpdateRandomSeed update_random_seed = 4;</code>
     * @return \Coresdk\WorkflowActivation\UpdateRandomSeed|null
     */
    public function getUpdateRandomSeed()
    {
        return $this->readOneof(4);
    }

    public function hasUpdateRandomSeed()
    {
        return $this->hasOneof(4);
    }

    /**
     * Workflow was reset. The randomness seed must be updated.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.UpdateRandomSeed update_random_seed = 4;</code>
     * @param \Coresdk\WorkflowActivation\UpdateRandomSeed $var
     * @return $this
     */
    public function setUpdateRandomSeed($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\UpdateRandomSeed::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * A request to query the workflow was received. It is guaranteed that queries (one or more)
     * always come in their own activation after other mutating jobs.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.QueryWorkflow query_workflow = 5;</code>
     * @return \Coresdk\WorkflowActivation\QueryWorkflow|null
     */
    public function getQueryWorkflow()
    {
        return $this->readOneof(5);
    }

    public function hasQueryWorkflow()
    {
        return $this->hasOneof(5);
    }

    /**
     * A request to query the workflow was received. It is guaranteed that queries (one or more)
     * always come in their own activation after other mutating jobs.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.QueryWorkflow query_workflow = 5;</code>
     * @param \Coresdk\WorkflowActivation\QueryWorkflow $var
     * @return $this
     */
    public function setQueryWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\QueryWorkflow::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * A request to cancel the workflow was received.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.CancelWorkflow cancel_workflow = 6;</code>
     * @return \Coresdk\WorkflowActivation\CancelWorkflow|null
     */
    public function getCancelWorkflow()
    {
        return $this->readOneof(6);
    }

    public function hasCancelWorkflow()
    {
        return $this->hasOneof(6);
    }

    /**
     * A request to cancel the workflow was received.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.CancelWorkflow cancel_workflow = 6;</code>
     * @param \Coresdk\WorkflowActivation\CancelWorkflow $var
     * @return $this
     */
    public function setCancelWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\CancelWorkflow::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * A request to signal the workflow was received.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.SignalWorkflow signal_workflow = 7;</code>
     * @return \Coresdk\WorkflowActivation\SignalWorkflow|null
     */
    public function getSignalWorkflow()
    {
        return $this->readOneof(7);
    }

    public function hasSignalWorkflow()
    {
        return $this->hasOneof(7);
    }

    /**
     * A request to signal the workflow was received.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.SignalWorkflow signal_workflow = 7;</code>
     * @param \Coresdk\WorkflowActivation\SignalWorkflow $var
     * @return $this
     */
    public function setSignalWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\SignalWorkflow::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * An activity was resolved, result could be completed, failed or cancelled
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveActivity resolve_activity = 8;</code>
     * @return \Coresdk\WorkflowActivation\ResolveActivity|null
     */
    public function getResolveActivity()
    {
        return $this->readOneof(8);
    }

    public function hasResolveActivity()
    {
        return $this->hasOneof(8);
    }

    /**
     * An activity was resolved, result could be completed, failed or cancelled
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveActivity resolve_activity = 8;</code>
     * @param \Coresdk\WorkflowActivation\ResolveActivity $var
     * @return $this
     */
    public function setResolveActivity($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveActivity::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * A patch marker has been detected and lang is being told that change exists. This
     * job is strange in that it is sent pre-emptively to lang without any corresponding
     * command being sent first.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.NotifyHasPatch notify_has_patch = 9;</code>
     * @return \Coresdk\WorkflowActivation\NotifyHasPatch|null
     */
    public function getNotifyHasPatch()
    {
        return $this->readOneof(9);
    }

    public function hasNotifyHasPatch()
    {
        return $this->hasOneof(9);
    }

    /**
     * A patch marker has been detected and lang is being told that change exists. This
     * job is strange in that it is sent pre-emptively to lang without any corresponding
     * command being sent first.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.NotifyHasPatch notify_has_patch = 9;</code>
     * @param \Coresdk\WorkflowActivation\NotifyHasPatch $var
     * @return $this
     */
    public function setNotifyHasPatch($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\NotifyHasPatch::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * A child workflow execution has started or failed to start
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStart resolve_child_workflow_execution_start = 10;</code>
     * @return \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStart|null
     */
    public function getResolveChildWorkflowExecutionStart()
    {
        return $this->readOneof(10);
    }

    public function hasResolveChildWorkflowExecutionStart()
    {
        return $this->hasOneof(10);
    }

    /**
     * A child workflow execution has started or failed to start
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecutionStart resolve_child_workflow_execution_start = 10;</code>
     * @param \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStart $var
     * @return $this
     */
    public function setResolveChildWorkflowExecutionStart($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveChildWorkflowExecutionStart::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * A child workflow was resolved, result could be completed or failed
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecution resolve_child_workflow_execution = 11;</code>
     * @return \Coresdk\WorkflowActivation\ResolveChildWorkflowExecution|null
     */
    public function getResolveChildWorkflowExecution()
    {
        return $this->readOneof(11);
    }

    public function hasResolveChildWorkflowExecution()
    {
        return $this->hasOneof(11);
    }

    /**
     * A child workflow was resolved, result could be completed or failed
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveChildWorkflowExecution resolve_child_workflow_execution = 11;</code>
     * @param \Coresdk\WorkflowActivation\ResolveChildWorkflowExecution $var
     * @return $this
     */
    public function setResolveChildWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveChildWorkflowExecution::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * An attempt to signal an external workflow resolved
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveSignalExternalWorkflow resolve_signal_external_workflow = 12;</code>
     * @return \Coresdk\WorkflowActivation\ResolveSignalExternalWorkflow|null
     */
    public function getResolveSignalExternalWorkflow()
    {
        return $this->readOneof(12);
    }

    public function hasResolveSignalExternalWorkflow()
    {
        return $this->hasOneof(12);
    }

    /**
     * An attempt to signal an external workflow resolved
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveSignalExternalWorkflow resolve_signal_external_workflow = 12;</code>
     * @param \Coresdk\WorkflowActivation\ResolveSignalExternalWorkflow $var
     * @return $this
     */
    public function setResolveSignalExternalWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveSignalExternalWorkflow::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * An attempt to cancel an external workflow resolved
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveRequestCancelExternalWorkflow resolve_request_cancel_external_workflow = 13;</code>
     * @return \Coresdk\WorkflowActivation\ResolveRequestCancelExternalWorkflow|null
     */
    public function getResolveRequestCancelExternalWorkflow()
    {
        return $this->readOneof(13);
    }

    public function hasResolveRequestCancelExternalWorkflow()
    {
        return $this->hasOneof(13);
    }

    /**
     * An attempt to cancel an external workflow resolved
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveRequestCancelExternalWorkflow resolve_request_cancel_external_workflow = 13;</code>
     * @param \Coresdk\WorkflowActivation\ResolveRequestCancelExternalWorkflow $var
     * @return $this
     */
    public function setResolveRequestCancelExternalWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveRequestCancelExternalWorkflow::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * A request to handle a workflow update.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.DoUpdate do_update = 14;</code>
     * @return \Coresdk\WorkflowActivation\DoUpdate|null
     */
    public function getDoUpdate()
    {
        return $this->readOneof(14);
    }

    public function hasDoUpdate()
    {
        return $this->hasOneof(14);
    }

    /**
     * A request to handle a workflow update.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.DoUpdate do_update = 14;</code>
     * @param \Coresdk\WorkflowActivation\DoUpdate $var
     * @return $this
     */
    public function setDoUpdate($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\DoUpdate::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * A nexus operation started.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveNexusOperationStart resolve_nexus_operation_start = 15;</code>
     * @return \Coresdk\WorkflowActivation\ResolveNexusOperationStart|null
     */
    public function getResolveNexusOperationStart()
    {
        return $this->readOneof(15);
    }

    public function hasResolveNexusOperationStart()
    {
        return $this->hasOneof(15);
    }

    /**
     * A nexus operation started.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveNexusOperationStart resolve_nexus_operation_start = 15;</code>
     * @param \Coresdk\WorkflowActivation\ResolveNexusOperationStart $var
     * @return $this
     */
    public function setResolveNexusOperationStart($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveNexusOperationStart::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * A nexus operation resolved.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveNexusOperation resolve_nexus_operation = 16;</code>
     * @return \Coresdk\WorkflowActivation\ResolveNexusOperation|null
     */
    public function getResolveNexusOperation()
    {
        return $this->readOneof(16);
    }

    public function hasResolveNexusOperation()
    {
        return $this->hasOneof(16);
    }

    /**
     * A nexus operation resolved.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.ResolveNexusOperation resolve_nexus_operation = 16;</code>
     * @param \Coresdk\WorkflowActivation\ResolveNexusOperation $var
     * @return $this
     */
    public function setResolveNexusOperation($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\ResolveNexusOperation::class);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Remove the workflow identified by the [WorkflowActivation] containing this job from the
     * cache after performing the activation. It is guaranteed that this will be the only job
     * in the activation if present.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.RemoveFromCache remove_from_cache = 50;</code>
     * @return \Coresdk\WorkflowActivation\RemoveFromCache|null
     */
    public function getRemoveFromCache()
    {
        return $this->readOneof(50);
    }

    public function hasRemoveFromCache()
    {
        return $this->hasOneof(50);
    }

    /**
     * Remove the workflow identified by the [WorkflowActivation] containing this job from the
     * cache after performing the activation. It is guaranteed that this will be the only job
     * in the activation if present.
     *
     * Generated from protobuf field <code>.coresdk.workflow_activation.RemoveFromCache remove_from_cache = 50;</code>
     * @param \Coresdk\WorkflowActivation\RemoveFromCache $var
     * @return $this
     */
    public function setRemoveFromCache($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowActivation\RemoveFromCache::class);
        $this->writeOneof(50, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVariant()
    {
        return $this->whichOneof("variant");
    }

}

