<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\WorkflowActivation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An instruction to the lang sdk to run some workflow code, whether for the first time or from
 * a cached state.
 * ## Job ordering guarantees and semantics
 * Core will, by default, order jobs within the activation as follows:
 * 1. init workflow
 * 2. patches
 * 3. random-seed-updates
 * 4. signals/updates
 * 5. all others
 * 6. local activity resolutions
 * 7. queries
 * 8. evictions
 * This is because:
 * * Patches are expected to apply to the entire activation
 * * Signal and update handlers should be invoked before workflow routines are iterated. That is to
 *  say before the users' main workflow function and anything spawned by it is allowed to continue.
 * * Local activities resolutions go after other normal jobs because while *not* replaying, they
 *  will always take longer than anything else that produces an immediate job (which is
 *  effectively instant). When *replaying* we need to scan ahead for LA markers so that we can
 *  resolve them in the same activation that they completed in when not replaying. However, doing
 *  so would, by default, put those resolutions *before* any other immediate jobs that happened
 *  in that same activation (prime example: cancelling not-wait-for-cancel activities). So, we do
 *  this to ensure the LA resolution happens after that cancel (or whatever else it may be) as it
 *  normally would have when executing.
 * * Queries always go last (and, in fact, always come in their own activation)
 * * Evictions also always come in their own activation
 * Core does this reordering to ensure that langs observe jobs in the same order during replay as
 * they would have during execution. However, in principle, this ordering is not necessary
 * (excepting queries/evictions, which definitely must come last) if lang layers apply all jobs to
 * state *first* (by resolving promises/futures, marking handlers to be invoked, etc as they iterate
 * over the jobs) and then only *after* that is done, drive coroutines/threads/whatever. If
 * execution works this way, then determinism is only impacted by the order routines are driven in
 * (which must be stable based on lang implementation or convention), rather than the order jobs are
 * processed.
 * ## Evictions
 * Evictions appear as an activations that contains only a `remove_from_cache` job. Such activations
 * should not cause the workflow code to be invoked and may be responded to with an empty command
 * list.
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.WorkflowActivation</code>
 */
class WorkflowActivation extends \Google\Protobuf\Internal\Message
{
    /**
     * The id of the currently active run of the workflow. Also used as a cache key. There may
     * only ever be one active workflow task (and hence activation) of a run at one time.
     *
     * Generated from protobuf field <code>string run_id = 1;</code>
     */
    protected $run_id = '';
    /**
     * The current time as understood by the workflow, which is set by workflow task started events
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    protected $timestamp = null;
    /**
     * Whether or not the activation is replaying past events
     *
     * Generated from protobuf field <code>bool is_replaying = 3;</code>
     */
    protected $is_replaying = false;
    /**
     * Current history length as determined by the event id of the most recently processed event.
     * This ensures that the number is always deterministic
     *
     * Generated from protobuf field <code>uint32 history_length = 4;</code>
     */
    protected $history_length = 0;
    /**
     * The things to do upon activating the workflow
     *
     * Generated from protobuf field <code>repeated .coresdk.workflow_activation.WorkflowActivationJob jobs = 5;</code>
     */
    private $jobs;
    /**
     * Internal flags which are available for use by lang. If `is_replaying` is false, all
     * internal flags may be used. This is not a delta - all previously used flags always
     * appear since this representation is cheap.
     *
     * Generated from protobuf field <code>repeated uint32 available_internal_flags = 6;</code>
     */
    private $available_internal_flags;
    /**
     * The history size in bytes as of the last WFT started event
     *
     * Generated from protobuf field <code>uint64 history_size_bytes = 7;</code>
     */
    protected $history_size_bytes = 0;
    /**
     * Set true if the most recent WFT started event had this suggestion
     *
     * Generated from protobuf field <code>bool continue_as_new_suggested = 8;</code>
     */
    protected $continue_as_new_suggested = false;
    /**
     * Set to the deployment version of the worker that processed this task,
     * which may be empty. During replay this version may not equal the version
     * of the replaying worker. If not replaying and this worker has a defined
     * Deployment Version, it will equal that. It will also be empty for
     * evict-only activations. The deployment name may be empty, but not the
     * build id, if this worker was using the deprecated Build ID-only
     * feature(s).
     *
     * Generated from protobuf field <code>.coresdk.common.WorkerDeploymentVersion deployment_version_for_current_task = 9;</code>
     */
    protected $deployment_version_for_current_task = null;
    /**
     * The last seen SDK version from the most recent WFT completed event
     *
     * Generated from protobuf field <code>string last_sdk_version = 10;</code>
     */
    protected $last_sdk_version = '';
    /**
     * Experimental. Optionally decide the versioning behavior that the first task of the new run should use.
     * For example, choose to AutoUpgrade on continue-as-new instead of inheriting the pinned version
     * of the previous run.
     *
     * Generated from protobuf field <code>repeated .temporal.api.enums.v1.SuggestContinueAsNewReason suggest_continue_as_new_reasons = 11;</code>
     */
    private $suggest_continue_as_new_reasons;
    /**
     * True if Workflow's Target Worker Deployment Version is different from its Pinned Version and
     * the workflow is Pinned.
     * Experimental.
     *
     * Generated from protobuf field <code>bool target_worker_deployment_version_changed = 12;</code>
     */
    protected $target_worker_deployment_version_changed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $run_id
     *           The id of the currently active run of the workflow. Also used as a cache key. There may
     *           only ever be one active workflow task (and hence activation) of a run at one time.
     *     @type \Google\Protobuf\Timestamp $timestamp
     *           The current time as understood by the workflow, which is set by workflow task started events
     *     @type bool $is_replaying
     *           Whether or not the activation is replaying past events
     *     @type int $history_length
     *           Current history length as determined by the event id of the most recently processed event.
     *           This ensures that the number is always deterministic
     *     @type array<\Coresdk\WorkflowActivation\WorkflowActivationJob>|\Google\Protobuf\Internal\RepeatedField $jobs
     *           The things to do upon activating the workflow
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $available_internal_flags
     *           Internal flags which are available for use by lang. If `is_replaying` is false, all
     *           internal flags may be used. This is not a delta - all previously used flags always
     *           appear since this representation is cheap.
     *     @type int|string $history_size_bytes
     *           The history size in bytes as of the last WFT started event
     *     @type bool $continue_as_new_suggested
     *           Set true if the most recent WFT started event had this suggestion
     *     @type \Coresdk\Common\WorkerDeploymentVersion $deployment_version_for_current_task
     *           Set to the deployment version of the worker that processed this task,
     *           which may be empty. During replay this version may not equal the version
     *           of the replaying worker. If not replaying and this worker has a defined
     *           Deployment Version, it will equal that. It will also be empty for
     *           evict-only activations. The deployment name may be empty, but not the
     *           build id, if this worker was using the deprecated Build ID-only
     *           feature(s).
     *     @type string $last_sdk_version
     *           The last seen SDK version from the most recent WFT completed event
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $suggest_continue_as_new_reasons
     *           Experimental. Optionally decide the versioning behavior that the first task of the new run should use.
     *           For example, choose to AutoUpgrade on continue-as-new instead of inheriting the pinned version
     *           of the previous run.
     *     @type bool $target_worker_deployment_version_changed
     *           True if Workflow's Target Worker Deployment Version is different from its Pinned Version and
     *           the workflow is Pinned.
     *           Experimental.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * The id of the currently active run of the workflow. Also used as a cache key. There may
     * only ever be one active workflow task (and hence activation) of a run at one time.
     *
     * Generated from protobuf field <code>string run_id = 1;</code>
     * @return string
     */
    public function getRunId()
    {
        return $this->run_id;
    }

    /**
     * The id of the currently active run of the workflow. Also used as a cache key. There may
     * only ever be one active workflow task (and hence activation) of a run at one time.
     *
     * Generated from protobuf field <code>string run_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRunId($var)
    {
        GPBUtil::checkString($var, True);
        $this->run_id = $var;

        return $this;
    }

    /**
     * The current time as understood by the workflow, which is set by workflow task started events
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * The current time as understood by the workflow, which is set by workflow task started events
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Whether or not the activation is replaying past events
     *
     * Generated from protobuf field <code>bool is_replaying = 3;</code>
     * @return bool
     */
    public function getIsReplaying()
    {
        return $this->is_replaying;
    }

    /**
     * Whether or not the activation is replaying past events
     *
     * Generated from protobuf field <code>bool is_replaying = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReplaying($var)
    {
        GPBUtil::checkBool($var);
        $this->is_replaying = $var;

        return $this;
    }

    /**
     * Current history length as determined by the event id of the most recently processed event.
     * This ensures that the number is always deterministic
     *
     * Generated from protobuf field <code>uint32 history_length = 4;</code>
     * @return int
     */
    public function getHistoryLength()
    {
        return $this->history_length;
    }

    /**
     * Current history length as determined by the event id of the most recently processed event.
     * This ensures that the number is always deterministic
     *
     * Generated from protobuf field <code>uint32 history_length = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setHistoryLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->history_length = $var;

        return $this;
    }

    /**
     * The things to do upon activating the workflow
     *
     * Generated from protobuf field <code>repeated .coresdk.workflow_activation.WorkflowActivationJob jobs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJobs()
    {
        return $this->jobs;
    }

    /**
     * The things to do upon activating the workflow
     *
     * Generated from protobuf field <code>repeated .coresdk.workflow_activation.WorkflowActivationJob jobs = 5;</code>
     * @param array<\Coresdk\WorkflowActivation\WorkflowActivationJob>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJobs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Coresdk\WorkflowActivation\WorkflowActivationJob::class);
        $this->jobs = $arr;

        return $this;
    }

    /**
     * Internal flags which are available for use by lang. If `is_replaying` is false, all
     * internal flags may be used. This is not a delta - all previously used flags always
     * appear since this representation is cheap.
     *
     * Generated from protobuf field <code>repeated uint32 available_internal_flags = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAvailableInternalFlags()
    {
        return $this->available_internal_flags;
    }

    /**
     * Internal flags which are available for use by lang. If `is_replaying` is false, all
     * internal flags may be used. This is not a delta - all previously used flags always
     * appear since this representation is cheap.
     *
     * Generated from protobuf field <code>repeated uint32 available_internal_flags = 6;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAvailableInternalFlags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->available_internal_flags = $arr;

        return $this;
    }

    /**
     * The history size in bytes as of the last WFT started event
     *
     * Generated from protobuf field <code>uint64 history_size_bytes = 7;</code>
     * @return int|string
     */
    public function getHistorySizeBytes()
    {
        return $this->history_size_bytes;
    }

    /**
     * The history size in bytes as of the last WFT started event
     *
     * Generated from protobuf field <code>uint64 history_size_bytes = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHistorySizeBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->history_size_bytes = $var;

        return $this;
    }

    /**
     * Set true if the most recent WFT started event had this suggestion
     *
     * Generated from protobuf field <code>bool continue_as_new_suggested = 8;</code>
     * @return bool
     */
    public function getContinueAsNewSuggested()
    {
        return $this->continue_as_new_suggested;
    }

    /**
     * Set true if the most recent WFT started event had this suggestion
     *
     * Generated from protobuf field <code>bool continue_as_new_suggested = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setContinueAsNewSuggested($var)
    {
        GPBUtil::checkBool($var);
        $this->continue_as_new_suggested = $var;

        return $this;
    }

    /**
     * Set to the deployment version of the worker that processed this task,
     * which may be empty. During replay this version may not equal the version
     * of the replaying worker. If not replaying and this worker has a defined
     * Deployment Version, it will equal that. It will also be empty for
     * evict-only activations. The deployment name may be empty, but not the
     * build id, if this worker was using the deprecated Build ID-only
     * feature(s).
     *
     * Generated from protobuf field <code>.coresdk.common.WorkerDeploymentVersion deployment_version_for_current_task = 9;</code>
     * @return \Coresdk\Common\WorkerDeploymentVersion|null
     */
    public function getDeploymentVersionForCurrentTask()
    {
        return $this->deployment_version_for_current_task;
    }

    public function hasDeploymentVersionForCurrentTask()
    {
        return isset($this->deployment_version_for_current_task);
    }

    public function clearDeploymentVersionForCurrentTask()
    {
        unset($this->deployment_version_for_current_task);
    }

    /**
     * Set to the deployment version of the worker that processed this task,
     * which may be empty. During replay this version may not equal the version
     * of the replaying worker. If not replaying and this worker has a defined
     * Deployment Version, it will equal that. It will also be empty for
     * evict-only activations. The deployment name may be empty, but not the
     * build id, if this worker was using the deprecated Build ID-only
     * feature(s).
     *
     * Generated from protobuf field <code>.coresdk.common.WorkerDeploymentVersion deployment_version_for_current_task = 9;</code>
     * @param \Coresdk\Common\WorkerDeploymentVersion $var
     * @return $this
     */
    public function setDeploymentVersionForCurrentTask($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\Common\WorkerDeploymentVersion::class);
        $this->deployment_version_for_current_task = $var;

        return $this;
    }

    /**
     * The last seen SDK version from the most recent WFT completed event
     *
     * Generated from protobuf field <code>string last_sdk_version = 10;</code>
     * @return string
     */
    public function getLastSdkVersion()
    {
        return $this->last_sdk_version;
    }

    /**
     * The last seen SDK version from the most recent WFT completed event
     *
     * Generated from protobuf field <code>string last_sdk_version = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLastSdkVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_sdk_version = $var;

        return $this;
    }

    /**
     * Experimental. Optionally decide the versioning behavior that the first task of the new run should use.
     * For example, choose to AutoUpgrade on continue-as-new instead of inheriting the pinned version
     * of the previous run.
     *
     * Generated from protobuf field <code>repeated .temporal.api.enums.v1.SuggestContinueAsNewReason suggest_continue_as_new_reasons = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSuggestContinueAsNewReasons()
    {
        return $this->suggest_continue_as_new_reasons;
    }

    /**
     * Experimental. Optionally decide the versioning behavior that the first task of the new run should use.
     * For example, choose to AutoUpgrade on continue-as-new instead of inheriting the pinned version
     * of the previous run.
     *
     * Generated from protobuf field <code>repeated .temporal.api.enums.v1.SuggestContinueAsNewReason suggest_continue_as_new_reasons = 11;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSuggestContinueAsNewReasons($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Temporal\Api\Enums\V1\SuggestContinueAsNewReason::class);
        $this->suggest_continue_as_new_reasons = $arr;

        return $this;
    }

    /**
     * True if Workflow's Target Worker Deployment Version is different from its Pinned Version and
     * the workflow is Pinned.
     * Experimental.
     *
     * Generated from protobuf field <code>bool target_worker_deployment_version_changed = 12;</code>
     * @return bool
     */
    public function getTargetWorkerDeploymentVersionChanged()
    {
        return $this->target_worker_deployment_version_changed;
    }

    /**
     * True if Workflow's Target Worker Deployment Version is different from its Pinned Version and
     * the workflow is Pinned.
     * Experimental.
     *
     * Generated from protobuf field <code>bool target_worker_deployment_version_changed = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setTargetWorkerDeploymentVersionChanged($var)
    {
        GPBUtil::checkBool($var);
        $this->target_worker_deployment_version_changed = $var;

        return $this;
    }

}

