<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/child_workflow/child_workflow.proto

namespace Coresdk\ChildWorkflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Used by core to resolve child workflow executions.
 *
 * Generated from protobuf message <code>coresdk.child_workflow.ChildWorkflowResult</code>
 */
class ChildWorkflowResult extends \Google\Protobuf\Internal\Message
{
    protected $status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Coresdk\ChildWorkflow\Success $completed
     *     @type \Coresdk\ChildWorkflow\Failure $failed
     *     @type \Coresdk\ChildWorkflow\Cancellation $cancelled
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\ChildWorkflow\ChildWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.Success completed = 1;</code>
     * @return \Coresdk\ChildWorkflow\Success|null
     */
    public function getCompleted()
    {
        return $this->readOneof(1);
    }

    public function hasCompleted()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.Success completed = 1;</code>
     * @param \Coresdk\ChildWorkflow\Success $var
     * @return $this
     */
    public function setCompleted($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ChildWorkflow\Success::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.Failure failed = 2;</code>
     * @return \Coresdk\ChildWorkflow\Failure|null
     */
    public function getFailed()
    {
        return $this->readOneof(2);
    }

    public function hasFailed()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.Failure failed = 2;</code>
     * @param \Coresdk\ChildWorkflow\Failure $var
     * @return $this
     */
    public function setFailed($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ChildWorkflow\Failure::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.Cancellation cancelled = 3;</code>
     * @return \Coresdk\ChildWorkflow\Cancellation|null
     */
    public function getCancelled()
    {
        return $this->readOneof(3);
    }

    public function hasCancelled()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.coresdk.child_workflow.Cancellation cancelled = 3;</code>
     * @param \Coresdk\ChildWorkflow\Cancellation $var
     * @return $this
     */
    public function setCancelled($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ChildWorkflow\Cancellation::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->whichOneof("status");
    }

}

