<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_commands/workflow_commands.proto

namespace Coresdk\Workflow_commands;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request cancellation of a nexus operation started via `ScheduleNexusOperation`
 *
 * Generated from protobuf message <code>coresdk.workflow_commands.RequestCancelNexusOperation</code>
 */
class RequestCancelNexusOperation extends \Google\Protobuf\Internal\Message
{
    /**
     * Lang's incremental sequence number as passed to `ScheduleNexusOperation`
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     */
    protected $seq = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seq
     *           Lang's incremental sequence number as passed to `ScheduleNexusOperation`
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowCommands\WorkflowCommands::initOnce();
        parent::__construct($data);
    }

    /**
     * Lang's incremental sequence number as passed to `ScheduleNexusOperation`
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Lang's incremental sequence number as passed to `ScheduleNexusOperation`
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

}

