<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_commands/workflow_commands.proto

namespace Coresdk\Workflow_commands;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A request to set/check if a certain patch is present or not
 *
 * Generated from protobuf message <code>coresdk.workflow_commands.SetPatchMarker</code>
 */
class SetPatchMarker extends \Google\Protobuf\Internal\Message
{
    /**
     * A user-chosen identifier for this patch. If the same identifier is used in multiple places in
     * the code, those places are considered to be versioned as one unit. IE: The check call will
     * return the same result for all of them
     *
     * Generated from protobuf field <code>string patch_id = 1;</code>
     */
    protected $patch_id = '';
    /**
     * Can be set to true to indicate that branches using this change are being removed, and all
     * future worker deployments will only have the "with change" code in them.
     *
     * Generated from protobuf field <code>bool deprecated = 2;</code>
     */
    protected $deprecated = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $patch_id
     *           A user-chosen identifier for this patch. If the same identifier is used in multiple places in
     *           the code, those places are considered to be versioned as one unit. IE: The check call will
     *           return the same result for all of them
     *     @type bool $deprecated
     *           Can be set to true to indicate that branches using this change are being removed, and all
     *           future worker deployments will only have the "with change" code in them.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowCommands\WorkflowCommands::initOnce();
        parent::__construct($data);
    }

    /**
     * A user-chosen identifier for this patch. If the same identifier is used in multiple places in
     * the code, those places are considered to be versioned as one unit. IE: The check call will
     * return the same result for all of them
     *
     * Generated from protobuf field <code>string patch_id = 1;</code>
     * @return string
     */
    public function getPatchId()
    {
        return $this->patch_id;
    }

    /**
     * A user-chosen identifier for this patch. If the same identifier is used in multiple places in
     * the code, those places are considered to be versioned as one unit. IE: The check call will
     * return the same result for all of them
     *
     * Generated from protobuf field <code>string patch_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPatchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->patch_id = $var;

        return $this;
    }

    /**
     * Can be set to true to indicate that branches using this change are being removed, and all
     * future worker deployments will only have the "with change" code in them.
     *
     * Generated from protobuf field <code>bool deprecated = 2;</code>
     * @return bool
     */
    public function getDeprecated()
    {
        return $this->deprecated;
    }

    /**
     * Can be set to true to indicate that branches using this change are being removed, and all
     * future worker deployments will only have the "with change" code in them.
     *
     * Generated from protobuf field <code>bool deprecated = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeprecated($var)
    {
        GPBUtil::checkBool($var);
        $this->deprecated = $var;

        return $this;
    }

}

