<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/activity_completion.proto

namespace GPBMetadata\Temporal\Sdk\Core;

class ActivityCompletion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Temporal\Api\Common\V1\Message::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\ActivityResult\ActivityResult::initOnce();
        $pool->internalAddGeneratedFile(
            '
Â
+temporal/sdk/core/activity_completion.protocoresdk7temporal/sdk/core/activity_result/activity_result.proto"Y
ActivityHeartbeat

task_token (0
details (2.temporal.api.common.v1.Payload"n
ActivityTaskCompletion

task_token (@
result (20.coresdk.activity_result.ActivityExecutionResultbproto3'
        , true);

        static::$is_initialized = true;
    }
}

