<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/core_interface.proto

namespace GPBMetadata\Temporal\Sdk\Core;

class CoreInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Temporal\Api\Common\V1\Message::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\ActivityResult\ActivityResult::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\ActivityTask\ActivityTask::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\Common\Common::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\ExternalData\ExternalData::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\WorkflowCommands\WorkflowCommands::initOnce();
        \GPBMetadata\Temporal\Sdk\Core\WorkflowCompletion\WorkflowCompletion::initOnce();
        $pool->internalAddGeneratedFile(
            '
‡	
&temporal/sdk/core/core_interface.protocoresdkgoogle/protobuf/empty.protogoogle/protobuf/timestamp.proto$temporal/api/common/v1/message.proto7temporal/sdk/core/activity_result/activity_result.proto3temporal/sdk/core/activity_task/activity_task.proto%temporal/sdk/core/common/common.proto3temporal/sdk/core/external_data/external_data.proto?temporal/sdk/core/workflow_activation/workflow_activation.proto;temporal/sdk/core/workflow_commands/workflow_commands.proto?temporal/sdk/core/workflow_completion/workflow_completion.proto"Y
ActivityHeartbeat

task_token (0
details (2.temporal.api.common.v1.Payload"n
ActivityTaskCompletion

task_token (@
result (20.coresdk.activity_result.ActivityExecutionResult"<
WorkflowSlotInfo
workflow_type (	
	is_sticky (")
ActivitySlotInfo
activity_type (	".
LocalActivitySlotInfo
activity_type (	"3
NexusSlotInfo
service (	
	operation (	"†
NamespaceInfo-
limits (2.coresdk.NamespaceInfo.LimitsF
Limits
blob_size_limit_error (
memo_size_limit_error (B=ÊCoresdkê0Temporalio::Internal::Bridge::Api::CoreInterfacebproto3'
        , true);

        static::$is_initialized = true;
    }
}

