<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/activity_result/activity_result.proto

namespace Coresdk\ActivityResult;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Used to report activity completions to core
 *
 * Generated from protobuf message <code>coresdk.activity_result.ActivityExecutionResult</code>
 */
class ActivityExecutionResult extends \Google\Protobuf\Internal\Message
{
    protected $status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Coresdk\ActivityResult\Success $completed
     *     @type \Coresdk\ActivityResult\Failure $failed
     *     @type \Coresdk\ActivityResult\Cancellation $cancelled
     *     @type \Coresdk\ActivityResult\WillCompleteAsync $will_complete_async
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\ActivityResult\ActivityResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.Success completed = 1;</code>
     * @return \Coresdk\ActivityResult\Success|null
     */
    public function getCompleted()
    {
        return $this->readOneof(1);
    }

    public function hasCompleted()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.Success completed = 1;</code>
     * @param \Coresdk\ActivityResult\Success $var
     * @return $this
     */
    public function setCompleted($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityResult\Success::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.Failure failed = 2;</code>
     * @return \Coresdk\ActivityResult\Failure|null
     */
    public function getFailed()
    {
        return $this->readOneof(2);
    }

    public function hasFailed()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.Failure failed = 2;</code>
     * @param \Coresdk\ActivityResult\Failure $var
     * @return $this
     */
    public function setFailed($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityResult\Failure::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.Cancellation cancelled = 3;</code>
     * @return \Coresdk\ActivityResult\Cancellation|null
     */
    public function getCancelled()
    {
        return $this->readOneof(3);
    }

    public function hasCancelled()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.Cancellation cancelled = 3;</code>
     * @param \Coresdk\ActivityResult\Cancellation $var
     * @return $this
     */
    public function setCancelled($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityResult\Cancellation::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.WillCompleteAsync will_complete_async = 4;</code>
     * @return \Coresdk\ActivityResult\WillCompleteAsync|null
     */
    public function getWillCompleteAsync()
    {
        return $this->readOneof(4);
    }

    public function hasWillCompleteAsync()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.coresdk.activity_result.WillCompleteAsync will_complete_async = 4;</code>
     * @param \Coresdk\ActivityResult\WillCompleteAsync $var
     * @return $this
     */
    public function setWillCompleteAsync($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityResult\WillCompleteAsync::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->whichOneof("status");
    }

}

