<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/callback/v1/message.proto

namespace GPBMetadata\Temporal\Api\Callback\V1;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Temporal\Api\Common\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\Common::initOnce();
        \GPBMetadata\Temporal\Api\Failure\V1\Message::initOnce();
        $pool->internalAddGeneratedFile(
            '
ë
&temporal/api/callback/v1/message.prototemporal.api.callback.v1$temporal/api/common/v1/message.proto"temporal/api/enums/v1/common.proto%temporal/api/failure/v1/message.proto"—
CallbackInfo2
callback (2 .temporal.api.common.v1.Callback5
registration_time (2.google.protobuf.Timestamp3
state (2$.temporal.api.enums.v1.CallbackState
attempt (>
last_attempt_complete_time (2.google.protobuf.Timestamp>
last_attempt_failure (2 .temporal.api.failure.v1.Failure>
next_attempt_schedule_time (2.google.protobuf.Timestamp
blocked_reason (	B“
io.temporal.api.callback.v1BMessageProtoPZ\'go.temporal.io/api/callback/v1;callbackªTemporalio.Api.Callback.V1êTemporalio::Api::Callback::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

