<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/activity_task/activity_task.proto

namespace Coresdk\ActivityTask;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>coresdk.activity_task.ActivityTask</code>
 */
class ActivityTask extends \Google\Protobuf\Internal\Message
{
    /**
     * A unique identifier for this task
     *
     * Generated from protobuf field <code>bytes task_token = 1;</code>
     */
    protected $task_token = '';
    protected $variant;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_token
     *           A unique identifier for this task
     *     @type \Coresdk\ActivityTask\Start $start
     *           Start activity execution.
     *     @type \Coresdk\ActivityTask\Cancel $cancel
     *           Attempt to cancel activity execution.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\ActivityTask\ActivityTask::initOnce();
        parent::__construct($data);
    }

    /**
     * A unique identifier for this task
     *
     * Generated from protobuf field <code>bytes task_token = 1;</code>
     * @return string
     */
    public function getTaskToken()
    {
        return $this->task_token;
    }

    /**
     * A unique identifier for this task
     *
     * Generated from protobuf field <code>bytes task_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->task_token = $var;

        return $this;
    }

    /**
     * Start activity execution.
     *
     * Generated from protobuf field <code>.coresdk.activity_task.Start start = 3;</code>
     * @return \Coresdk\ActivityTask\Start|null
     */
    public function getStart()
    {
        return $this->readOneof(3);
    }

    public function hasStart()
    {
        return $this->hasOneof(3);
    }

    /**
     * Start activity execution.
     *
     * Generated from protobuf field <code>.coresdk.activity_task.Start start = 3;</code>
     * @param \Coresdk\ActivityTask\Start $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityTask\Start::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Attempt to cancel activity execution.
     *
     * Generated from protobuf field <code>.coresdk.activity_task.Cancel cancel = 4;</code>
     * @return \Coresdk\ActivityTask\Cancel|null
     */
    public function getCancel()
    {
        return $this->readOneof(4);
    }

    public function hasCancel()
    {
        return $this->hasOneof(4);
    }

    /**
     * Attempt to cancel activity execution.
     *
     * Generated from protobuf field <code>.coresdk.activity_task.Cancel cancel = 4;</code>
     * @param \Coresdk\ActivityTask\Cancel $var
     * @return $this
     */
    public function setCancel($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityTask\Cancel::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVariant()
    {
        return $this->whichOneof("variant");
    }

}

