<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/activity_task/activity_task.proto

namespace Coresdk\ActivityTask;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Attempt to cancel a running activity
 *
 * Generated from protobuf message <code>coresdk.activity_task.Cancel</code>
 */
class Cancel extends \Google\Protobuf\Internal\Message
{
    /**
     * Primary cancellation reason
     *
     * Generated from protobuf field <code>.coresdk.activity_task.ActivityCancelReason reason = 1;</code>
     */
    protected $reason = 0;
    /**
     * Activity cancellation details, surfaces all cancellation reasons.
     *
     * Generated from protobuf field <code>.coresdk.activity_task.ActivityCancellationDetails details = 2;</code>
     */
    protected $details = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $reason
     *           Primary cancellation reason
     *     @type \Coresdk\ActivityTask\ActivityCancellationDetails $details
     *           Activity cancellation details, surfaces all cancellation reasons.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\ActivityTask\ActivityTask::initOnce();
        parent::__construct($data);
    }

    /**
     * Primary cancellation reason
     *
     * Generated from protobuf field <code>.coresdk.activity_task.ActivityCancelReason reason = 1;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Primary cancellation reason
     *
     * Generated from protobuf field <code>.coresdk.activity_task.ActivityCancelReason reason = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Coresdk\ActivityTask\ActivityCancelReason::class);
        $this->reason = $var;

        return $this;
    }

    /**
     * Activity cancellation details, surfaces all cancellation reasons.
     *
     * Generated from protobuf field <code>.coresdk.activity_task.ActivityCancellationDetails details = 2;</code>
     * @return \Coresdk\ActivityTask\ActivityCancellationDetails|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Activity cancellation details, surfaces all cancellation reasons.
     *
     * Generated from protobuf field <code>.coresdk.activity_task.ActivityCancellationDetails details = 2;</code>
     * @param \Coresdk\ActivityTask\ActivityCancellationDetails $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\ActivityTask\ActivityCancellationDetails::class);
        $this->details = $var;

        return $this;
    }

}

