<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/common/v1/message.proto

namespace Temporal\Api\Common\V1;

if (false) {
    /**
     * This class is deprecated. Use Temporal\Api\Common\V1\Link\NexusOperation instead.
     * @deprecated
     */
    class Link_NexusOperation {}
}
class_exists(Link\NexusOperation::class);
@trigger_error('Temporal\Api\Common\V1\Link_NexusOperation is deprecated and will be removed in the next major release. Use Temporal\Api\Common\V1\Link\NexusOperation instead', E_USER_DEPRECATED);

