<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/common/v1/message.proto

namespace Temporal\Api\Common\V1;

if (false) {
    /**
     * This class is deprecated. Use Temporal\Api\Common\V1\Link\Activity instead.
     * @deprecated
     */
    class Link_Activity {}
}
class_exists(Link\Activity::class);
@trigger_error('Temporal\Api\Common\V1\Link_Activity is deprecated and will be removed in the next major release. Use Temporal\Api\Common\V1\Link\Activity instead', E_USER_DEPRECATED);

