<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_commands/workflow_commands.proto

namespace Coresdk\WorkflowCommands;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Send a signal to an external or child workflow
 *
 * Generated from protobuf message <code>coresdk.workflow_commands.SignalExternalWorkflowExecution</code>
 */
class SignalExternalWorkflowExecution extends \Google\Protobuf\Internal\Message
{
    /**
     * Lang's incremental sequence number, used as the operation identifier
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     */
    protected $seq = 0;
    /**
     * Name of the signal handler
     *
     * Generated from protobuf field <code>string signal_name = 4;</code>
     */
    protected $signal_name = '';
    /**
     * Arguments for the handler
     *
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload args = 5;</code>
     */
    private $args;
    /**
     * Headers to attach to the signal
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 6;</code>
     */
    private $headers;
    protected $target;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seq
     *           Lang's incremental sequence number, used as the operation identifier
     *     @type \Coresdk\Common\NamespacedWorkflowExecution $workflow_execution
     *           A specific workflow instance
     *     @type string $child_workflow_id
     *           The desired target must be a child of the issuing workflow, and this is its workflow id
     *     @type string $signal_name
     *           Name of the signal handler
     *     @type array<\Temporal\Api\Common\V1\Payload>|\Google\Protobuf\Internal\RepeatedField $args
     *           Arguments for the handler
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     *           Headers to attach to the signal
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowCommands\WorkflowCommands::initOnce();
        parent::__construct($data);
    }

    /**
     * Lang's incremental sequence number, used as the operation identifier
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Lang's incremental sequence number, used as the operation identifier
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * A specific workflow instance
     *
     * Generated from protobuf field <code>.coresdk.common.NamespacedWorkflowExecution workflow_execution = 2;</code>
     * @return \Coresdk\Common\NamespacedWorkflowExecution|null
     */
    public function getWorkflowExecution()
    {
        return $this->readOneof(2);
    }

    public function hasWorkflowExecution()
    {
        return $this->hasOneof(2);
    }

    /**
     * A specific workflow instance
     *
     * Generated from protobuf field <code>.coresdk.common.NamespacedWorkflowExecution workflow_execution = 2;</code>
     * @param \Coresdk\Common\NamespacedWorkflowExecution $var
     * @return $this
     */
    public function setWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\Common\NamespacedWorkflowExecution::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * The desired target must be a child of the issuing workflow, and this is its workflow id
     *
     * Generated from protobuf field <code>string child_workflow_id = 3;</code>
     * @return string
     */
    public function getChildWorkflowId()
    {
        return $this->readOneof(3);
    }

    public function hasChildWorkflowId()
    {
        return $this->hasOneof(3);
    }

    /**
     * The desired target must be a child of the issuing workflow, and this is its workflow id
     *
     * Generated from protobuf field <code>string child_workflow_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChildWorkflowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Name of the signal handler
     *
     * Generated from protobuf field <code>string signal_name = 4;</code>
     * @return string
     */
    public function getSignalName()
    {
        return $this->signal_name;
    }

    /**
     * Name of the signal handler
     *
     * Generated from protobuf field <code>string signal_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->signal_name = $var;

        return $this;
    }

    /**
     * Arguments for the handler
     *
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload args = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Arguments for the handler
     *
     * Generated from protobuf field <code>repeated .temporal.api.common.v1.Payload args = 5;</code>
     * @param array<\Temporal\Api\Common\V1\Payload>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Common\V1\Payload::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Headers to attach to the signal
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Headers to attach to the signal
     *
     * Generated from protobuf field <code>map<string, .temporal.api.common.v1.Payload> headers = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Common\V1\Payload::class);
        $this->headers = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getTarget()
    {
        return $this->whichOneof("target");
    }

}

