<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_commands/workflow_commands.proto

namespace Coresdk\WorkflowCommands;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>coresdk.workflow_commands.WorkflowCommand</code>
 */
class WorkflowCommand extends \Google\Protobuf\Internal\Message
{
    /**
     * User metadata that may or may not be persisted into history depending on the command type.
     * Lang layers are expected to expose the setting of the internals of this metadata on a
     * per-command basis where applicable.
     *
     * Generated from protobuf field <code>.temporal.api.sdk.v1.UserMetadata user_metadata = 100;</code>
     */
    protected $user_metadata = null;
    protected $variant;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Temporal\Api\Sdk\V1\UserMetadata $user_metadata
     *           User metadata that may or may not be persisted into history depending on the command type.
     *           Lang layers are expected to expose the setting of the internals of this metadata on a
     *           per-command basis where applicable.
     *     @type \Coresdk\WorkflowCommands\StartTimer $start_timer
     *     @type \Coresdk\WorkflowCommands\ScheduleActivity $schedule_activity
     *     @type \Coresdk\WorkflowCommands\QueryResult $respond_to_query
     *     @type \Coresdk\WorkflowCommands\RequestCancelActivity $request_cancel_activity
     *     @type \Coresdk\WorkflowCommands\CancelTimer $cancel_timer
     *     @type \Coresdk\WorkflowCommands\CompleteWorkflowExecution $complete_workflow_execution
     *     @type \Coresdk\WorkflowCommands\FailWorkflowExecution $fail_workflow_execution
     *     @type \Coresdk\WorkflowCommands\ContinueAsNewWorkflowExecution $continue_as_new_workflow_execution
     *     @type \Coresdk\WorkflowCommands\CancelWorkflowExecution $cancel_workflow_execution
     *     @type \Coresdk\WorkflowCommands\SetPatchMarker $set_patch_marker
     *     @type \Coresdk\WorkflowCommands\StartChildWorkflowExecution $start_child_workflow_execution
     *     @type \Coresdk\WorkflowCommands\CancelChildWorkflowExecution $cancel_child_workflow_execution
     *     @type \Coresdk\WorkflowCommands\RequestCancelExternalWorkflowExecution $request_cancel_external_workflow_execution
     *     @type \Coresdk\WorkflowCommands\SignalExternalWorkflowExecution $signal_external_workflow_execution
     *     @type \Coresdk\WorkflowCommands\CancelSignalWorkflow $cancel_signal_workflow
     *     @type \Coresdk\WorkflowCommands\ScheduleLocalActivity $schedule_local_activity
     *     @type \Coresdk\WorkflowCommands\RequestCancelLocalActivity $request_cancel_local_activity
     *     @type \Coresdk\WorkflowCommands\UpsertWorkflowSearchAttributes $upsert_workflow_search_attributes
     *     @type \Coresdk\WorkflowCommands\ModifyWorkflowProperties $modify_workflow_properties
     *     @type \Coresdk\WorkflowCommands\UpdateResponse $update_response
     *     @type \Coresdk\WorkflowCommands\ScheduleNexusOperation $schedule_nexus_operation
     *     @type \Coresdk\WorkflowCommands\RequestCancelNexusOperation $request_cancel_nexus_operation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowCommands\WorkflowCommands::initOnce();
        parent::__construct($data);
    }

    /**
     * User metadata that may or may not be persisted into history depending on the command type.
     * Lang layers are expected to expose the setting of the internals of this metadata on a
     * per-command basis where applicable.
     *
     * Generated from protobuf field <code>.temporal.api.sdk.v1.UserMetadata user_metadata = 100;</code>
     * @return \Temporal\Api\Sdk\V1\UserMetadata|null
     */
    public function getUserMetadata()
    {
        return $this->user_metadata;
    }

    public function hasUserMetadata()
    {
        return isset($this->user_metadata);
    }

    public function clearUserMetadata()
    {
        unset($this->user_metadata);
    }

    /**
     * User metadata that may or may not be persisted into history depending on the command type.
     * Lang layers are expected to expose the setting of the internals of this metadata on a
     * per-command basis where applicable.
     *
     * Generated from protobuf field <code>.temporal.api.sdk.v1.UserMetadata user_metadata = 100;</code>
     * @param \Temporal\Api\Sdk\V1\UserMetadata $var
     * @return $this
     */
    public function setUserMetadata($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Sdk\V1\UserMetadata::class);
        $this->user_metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.StartTimer start_timer = 1;</code>
     * @return \Coresdk\WorkflowCommands\StartTimer|null
     */
    public function getStartTimer()
    {
        return $this->readOneof(1);
    }

    public function hasStartTimer()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.StartTimer start_timer = 1;</code>
     * @param \Coresdk\WorkflowCommands\StartTimer $var
     * @return $this
     */
    public function setStartTimer($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\StartTimer::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ScheduleActivity schedule_activity = 2;</code>
     * @return \Coresdk\WorkflowCommands\ScheduleActivity|null
     */
    public function getScheduleActivity()
    {
        return $this->readOneof(2);
    }

    public function hasScheduleActivity()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ScheduleActivity schedule_activity = 2;</code>
     * @param \Coresdk\WorkflowCommands\ScheduleActivity $var
     * @return $this
     */
    public function setScheduleActivity($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\ScheduleActivity::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.QueryResult respond_to_query = 3;</code>
     * @return \Coresdk\WorkflowCommands\QueryResult|null
     */
    public function getRespondToQuery()
    {
        return $this->readOneof(3);
    }

    public function hasRespondToQuery()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.QueryResult respond_to_query = 3;</code>
     * @param \Coresdk\WorkflowCommands\QueryResult $var
     * @return $this
     */
    public function setRespondToQuery($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\QueryResult::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelActivity request_cancel_activity = 4;</code>
     * @return \Coresdk\WorkflowCommands\RequestCancelActivity|null
     */
    public function getRequestCancelActivity()
    {
        return $this->readOneof(4);
    }

    public function hasRequestCancelActivity()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelActivity request_cancel_activity = 4;</code>
     * @param \Coresdk\WorkflowCommands\RequestCancelActivity $var
     * @return $this
     */
    public function setRequestCancelActivity($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\RequestCancelActivity::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelTimer cancel_timer = 5;</code>
     * @return \Coresdk\WorkflowCommands\CancelTimer|null
     */
    public function getCancelTimer()
    {
        return $this->readOneof(5);
    }

    public function hasCancelTimer()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelTimer cancel_timer = 5;</code>
     * @param \Coresdk\WorkflowCommands\CancelTimer $var
     * @return $this
     */
    public function setCancelTimer($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\CancelTimer::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CompleteWorkflowExecution complete_workflow_execution = 6;</code>
     * @return \Coresdk\WorkflowCommands\CompleteWorkflowExecution|null
     */
    public function getCompleteWorkflowExecution()
    {
        return $this->readOneof(6);
    }

    public function hasCompleteWorkflowExecution()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CompleteWorkflowExecution complete_workflow_execution = 6;</code>
     * @param \Coresdk\WorkflowCommands\CompleteWorkflowExecution $var
     * @return $this
     */
    public function setCompleteWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\CompleteWorkflowExecution::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.FailWorkflowExecution fail_workflow_execution = 7;</code>
     * @return \Coresdk\WorkflowCommands\FailWorkflowExecution|null
     */
    public function getFailWorkflowExecution()
    {
        return $this->readOneof(7);
    }

    public function hasFailWorkflowExecution()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.FailWorkflowExecution fail_workflow_execution = 7;</code>
     * @param \Coresdk\WorkflowCommands\FailWorkflowExecution $var
     * @return $this
     */
    public function setFailWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\FailWorkflowExecution::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ContinueAsNewWorkflowExecution continue_as_new_workflow_execution = 8;</code>
     * @return \Coresdk\WorkflowCommands\ContinueAsNewWorkflowExecution|null
     */
    public function getContinueAsNewWorkflowExecution()
    {
        return $this->readOneof(8);
    }

    public function hasContinueAsNewWorkflowExecution()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ContinueAsNewWorkflowExecution continue_as_new_workflow_execution = 8;</code>
     * @param \Coresdk\WorkflowCommands\ContinueAsNewWorkflowExecution $var
     * @return $this
     */
    public function setContinueAsNewWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\ContinueAsNewWorkflowExecution::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelWorkflowExecution cancel_workflow_execution = 9;</code>
     * @return \Coresdk\WorkflowCommands\CancelWorkflowExecution|null
     */
    public function getCancelWorkflowExecution()
    {
        return $this->readOneof(9);
    }

    public function hasCancelWorkflowExecution()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelWorkflowExecution cancel_workflow_execution = 9;</code>
     * @param \Coresdk\WorkflowCommands\CancelWorkflowExecution $var
     * @return $this
     */
    public function setCancelWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\CancelWorkflowExecution::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.SetPatchMarker set_patch_marker = 10;</code>
     * @return \Coresdk\WorkflowCommands\SetPatchMarker|null
     */
    public function getSetPatchMarker()
    {
        return $this->readOneof(10);
    }

    public function hasSetPatchMarker()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.SetPatchMarker set_patch_marker = 10;</code>
     * @param \Coresdk\WorkflowCommands\SetPatchMarker $var
     * @return $this
     */
    public function setSetPatchMarker($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\SetPatchMarker::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.StartChildWorkflowExecution start_child_workflow_execution = 11;</code>
     * @return \Coresdk\WorkflowCommands\StartChildWorkflowExecution|null
     */
    public function getStartChildWorkflowExecution()
    {
        return $this->readOneof(11);
    }

    public function hasStartChildWorkflowExecution()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.StartChildWorkflowExecution start_child_workflow_execution = 11;</code>
     * @param \Coresdk\WorkflowCommands\StartChildWorkflowExecution $var
     * @return $this
     */
    public function setStartChildWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\StartChildWorkflowExecution::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelChildWorkflowExecution cancel_child_workflow_execution = 12;</code>
     * @return \Coresdk\WorkflowCommands\CancelChildWorkflowExecution|null
     */
    public function getCancelChildWorkflowExecution()
    {
        return $this->readOneof(12);
    }

    public function hasCancelChildWorkflowExecution()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelChildWorkflowExecution cancel_child_workflow_execution = 12;</code>
     * @param \Coresdk\WorkflowCommands\CancelChildWorkflowExecution $var
     * @return $this
     */
    public function setCancelChildWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\CancelChildWorkflowExecution::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelExternalWorkflowExecution request_cancel_external_workflow_execution = 13;</code>
     * @return \Coresdk\WorkflowCommands\RequestCancelExternalWorkflowExecution|null
     */
    public function getRequestCancelExternalWorkflowExecution()
    {
        return $this->readOneof(13);
    }

    public function hasRequestCancelExternalWorkflowExecution()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelExternalWorkflowExecution request_cancel_external_workflow_execution = 13;</code>
     * @param \Coresdk\WorkflowCommands\RequestCancelExternalWorkflowExecution $var
     * @return $this
     */
    public function setRequestCancelExternalWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\RequestCancelExternalWorkflowExecution::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.SignalExternalWorkflowExecution signal_external_workflow_execution = 14;</code>
     * @return \Coresdk\WorkflowCommands\SignalExternalWorkflowExecution|null
     */
    public function getSignalExternalWorkflowExecution()
    {
        return $this->readOneof(14);
    }

    public function hasSignalExternalWorkflowExecution()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.SignalExternalWorkflowExecution signal_external_workflow_execution = 14;</code>
     * @param \Coresdk\WorkflowCommands\SignalExternalWorkflowExecution $var
     * @return $this
     */
    public function setSignalExternalWorkflowExecution($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\SignalExternalWorkflowExecution::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelSignalWorkflow cancel_signal_workflow = 15;</code>
     * @return \Coresdk\WorkflowCommands\CancelSignalWorkflow|null
     */
    public function getCancelSignalWorkflow()
    {
        return $this->readOneof(15);
    }

    public function hasCancelSignalWorkflow()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.CancelSignalWorkflow cancel_signal_workflow = 15;</code>
     * @param \Coresdk\WorkflowCommands\CancelSignalWorkflow $var
     * @return $this
     */
    public function setCancelSignalWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\CancelSignalWorkflow::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ScheduleLocalActivity schedule_local_activity = 16;</code>
     * @return \Coresdk\WorkflowCommands\ScheduleLocalActivity|null
     */
    public function getScheduleLocalActivity()
    {
        return $this->readOneof(16);
    }

    public function hasScheduleLocalActivity()
    {
        return $this->hasOneof(16);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ScheduleLocalActivity schedule_local_activity = 16;</code>
     * @param \Coresdk\WorkflowCommands\ScheduleLocalActivity $var
     * @return $this
     */
    public function setScheduleLocalActivity($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\ScheduleLocalActivity::class);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelLocalActivity request_cancel_local_activity = 17;</code>
     * @return \Coresdk\WorkflowCommands\RequestCancelLocalActivity|null
     */
    public function getRequestCancelLocalActivity()
    {
        return $this->readOneof(17);
    }

    public function hasRequestCancelLocalActivity()
    {
        return $this->hasOneof(17);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelLocalActivity request_cancel_local_activity = 17;</code>
     * @param \Coresdk\WorkflowCommands\RequestCancelLocalActivity $var
     * @return $this
     */
    public function setRequestCancelLocalActivity($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\RequestCancelLocalActivity::class);
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.UpsertWorkflowSearchAttributes upsert_workflow_search_attributes = 18;</code>
     * @return \Coresdk\WorkflowCommands\UpsertWorkflowSearchAttributes|null
     */
    public function getUpsertWorkflowSearchAttributes()
    {
        return $this->readOneof(18);
    }

    public function hasUpsertWorkflowSearchAttributes()
    {
        return $this->hasOneof(18);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.UpsertWorkflowSearchAttributes upsert_workflow_search_attributes = 18;</code>
     * @param \Coresdk\WorkflowCommands\UpsertWorkflowSearchAttributes $var
     * @return $this
     */
    public function setUpsertWorkflowSearchAttributes($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\UpsertWorkflowSearchAttributes::class);
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ModifyWorkflowProperties modify_workflow_properties = 19;</code>
     * @return \Coresdk\WorkflowCommands\ModifyWorkflowProperties|null
     */
    public function getModifyWorkflowProperties()
    {
        return $this->readOneof(19);
    }

    public function hasModifyWorkflowProperties()
    {
        return $this->hasOneof(19);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ModifyWorkflowProperties modify_workflow_properties = 19;</code>
     * @param \Coresdk\WorkflowCommands\ModifyWorkflowProperties $var
     * @return $this
     */
    public function setModifyWorkflowProperties($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\ModifyWorkflowProperties::class);
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.UpdateResponse update_response = 20;</code>
     * @return \Coresdk\WorkflowCommands\UpdateResponse|null
     */
    public function getUpdateResponse()
    {
        return $this->readOneof(20);
    }

    public function hasUpdateResponse()
    {
        return $this->hasOneof(20);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.UpdateResponse update_response = 20;</code>
     * @param \Coresdk\WorkflowCommands\UpdateResponse $var
     * @return $this
     */
    public function setUpdateResponse($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\UpdateResponse::class);
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ScheduleNexusOperation schedule_nexus_operation = 21;</code>
     * @return \Coresdk\WorkflowCommands\ScheduleNexusOperation|null
     */
    public function getScheduleNexusOperation()
    {
        return $this->readOneof(21);
    }

    public function hasScheduleNexusOperation()
    {
        return $this->hasOneof(21);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.ScheduleNexusOperation schedule_nexus_operation = 21;</code>
     * @param \Coresdk\WorkflowCommands\ScheduleNexusOperation $var
     * @return $this
     */
    public function setScheduleNexusOperation($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\ScheduleNexusOperation::class);
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelNexusOperation request_cancel_nexus_operation = 22;</code>
     * @return \Coresdk\WorkflowCommands\RequestCancelNexusOperation|null
     */
    public function getRequestCancelNexusOperation()
    {
        return $this->readOneof(22);
    }

    public function hasRequestCancelNexusOperation()
    {
        return $this->hasOneof(22);
    }

    /**
     * Generated from protobuf field <code>.coresdk.workflow_commands.RequestCancelNexusOperation request_cancel_nexus_operation = 22;</code>
     * @param \Coresdk\WorkflowCommands\RequestCancelNexusOperation $var
     * @return $this
     */
    public function setRequestCancelNexusOperation($var)
    {
        GPBUtil::checkMessage($var, \Coresdk\WorkflowCommands\RequestCancelNexusOperation::class);
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVariant()
    {
        return $this->whichOneof("variant");
    }

}

