<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/nexus/nexus.proto

namespace Coresdk\Nexus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>coresdk.nexus.CancelNexusTask</code>
 */
class CancelNexusTask extends \Google\Protobuf\Internal\Message
{
    /**
     * The task token from the PollNexusTaskQueueResponse
     *
     * Generated from protobuf field <code>bytes task_token = 1;</code>
     */
    protected $task_token = '';
    /**
     * Why Core is asking for this operation to be cancelled
     *
     * Generated from protobuf field <code>.coresdk.nexus.NexusTaskCancelReason reason = 2;</code>
     */
    protected $reason = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_token
     *           The task token from the PollNexusTaskQueueResponse
     *     @type int $reason
     *           Why Core is asking for this operation to be cancelled
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\Nexus\Nexus::initOnce();
        parent::__construct($data);
    }

    /**
     * The task token from the PollNexusTaskQueueResponse
     *
     * Generated from protobuf field <code>bytes task_token = 1;</code>
     * @return string
     */
    public function getTaskToken()
    {
        return $this->task_token;
    }

    /**
     * The task token from the PollNexusTaskQueueResponse
     *
     * Generated from protobuf field <code>bytes task_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->task_token = $var;

        return $this;
    }

    /**
     * Why Core is asking for this operation to be cancelled
     *
     * Generated from protobuf field <code>.coresdk.nexus.NexusTaskCancelReason reason = 2;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Why Core is asking for this operation to be cancelled
     *
     * Generated from protobuf field <code>.coresdk.nexus.NexusTaskCancelReason reason = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Coresdk\Nexus\NexusTaskCancelReason::class);
        $this->reason = $var;

        return $this;
    }

}

