<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

if (false) {
    /**
     * This class is deprecated. Use Temporal\Api\Workflowservice\V1\CountNexusOperationExecutionsResponse\AggregationGroup instead.
     * @deprecated
     */
    class CountNexusOperationExecutionsResponse_AggregationGroup {}
}
class_exists(CountNexusOperationExecutionsResponse\AggregationGroup::class);
@trigger_error('Temporal\Api\Workflowservice\V1\CountNexusOperationExecutionsResponse_AggregationGroup is deprecated and will be removed in the next major release. Use Temporal\Api\Workflowservice\V1\CountNexusOperationExecutionsResponse\AggregationGroup instead', E_USER_DEPRECATED);

