<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\Workflow_activation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Notify a workflow that a timer has fired
 *
 * Generated from protobuf message <code>coresdk.workflow_activation.FireTimer</code>
 */
class FireTimer extends \Google\Protobuf\Internal\Message
{
    /**
     * Sequence number as provided by lang in the corresponding StartTimer command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     */
    protected $seq = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seq
     *           Sequence number as provided by lang in the corresponding StartTimer command
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\WorkflowActivation\WorkflowActivation::initOnce();
        parent::__construct($data);
    }

    /**
     * Sequence number as provided by lang in the corresponding StartTimer command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Sequence number as provided by lang in the corresponding StartTimer command
     *
     * Generated from protobuf field <code>uint32 seq = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

}

