<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/workflow_activation/workflow_activation.proto

namespace Coresdk\Workflow_activation;

if (false) {
    /**
     * This class is deprecated. Use Coresdk\Workflow_activation\RemoveFromCache\EvictionReason instead.
     * @deprecated
     */
    class RemoveFromCache_EvictionReason {}
}
class_exists(RemoveFromCache\EvictionReason::class);
@trigger_error('Coresdk\Workflow_activation\RemoveFromCache_EvictionReason is deprecated and will be removed in the next major release. Use Coresdk\Workflow_activation\RemoveFromCache\EvictionReason instead', E_USER_DEPRECATED);

