on:
  workflow_call:
    inputs:
      test-suite:
        required: true
        type: string
      fail-fast:
        required: true
        type: boolean
        default: true

jobs:
  test:
    name: Testing ${{ inputs.test-suite }} (PHP ${{ matrix.php }}, OS ${{ matrix.os }}, ${{ matrix.prefer-lowest }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        php: [ 7.4 ] #, 8.0]
        os: [ ubuntu-latest ] #, windows-latest]
        prefer-lowest: [ --prefer-lowest, '' ]
    steps:
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: dom, sockets, grpc, curl

      - name: Check Out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer update
              ${{ matrix.prefer-lowest }}
              --prefer-stable
              --prefer-dist
              --no-interaction
              --no-progress

      - name: Download RoadRunner
        run: |
          vendor/bin/rr get --no-interaction --stability=stable

      - name: Run Tests
        run: vendor/bin/phpunit --testsuite=${{ inputs.test-suite }} --testdox --verbose
