name: Testing

on: [push, pull_request]

jobs:
  unit:
    name: Unit Testing
    uses: ./.github/workflows/run-test-suite.yml
    with:
      fail-fast: false
      test-suite: Unit

  feature:
    name: Feature Testing
    uses: ./.github/workflows/run-test-suite.yml
    with:
      fail-fast: true
      test-suite: Feature
      test-timeout: 20

  functional:
    name: Functional Testing
    uses: ./.github/workflows/run-test-suite.yml
    with:
      fail-fast: false
      test-suite: Functional
