name: Testing

on: [push, pull_request]

jobs:
#  security:
#    name: Security Checks (PHP ${{ matrix.php }}, OS ${{ matrix.os }})
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        # Note: This workflow requires only the LATEST version of PHP
#        php: [ 7.4 ]
#        os: [ ubuntu-latest ]
#    steps:
#      - name: Set up PHP ${{ matrix.php }}
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: dom, sockets, grpc, curl
#
#      - name: Check Out Code
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#
#      - name: Get Composer Cache Directory
#        # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
#        id: composer-cache
#        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
#
#      - name: Cache Dependencies
#        # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.composer-cache.outputs.dir }}
#          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
#          restore-keys: ${{ runner.os }}-composer-
#
#      - name: Install Composer Dependencies
#        run: composer install --prefer-dist --no-interaction --no-suggest
#
#      - name: Verify
#        run: composer require --dev roave/security-advisories:dev-latest

  unit:
    name: Unit Testing
    uses: .github/workflows/run-test-suite.yml
    with:
      fail-fast: false
      test-suite: Unit

  feature:
    name: Feature Testing
    uses: .github/workflows/run-test-suite.yml
    with:
      fail-fast: true
      test-suite: Feature
      test-timeout: 20

  functional:
    name: Functional Testing
    uses: .github/workflows/run-test-suite.yml
    with:
      fail-fast: false
      test-suite: Functional
