<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/core_interface.proto

namespace Coresdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Info about activity task slot usage
 *
 * Generated from protobuf message <code>coresdk.ActivitySlotInfo</code>
 */
class ActivitySlotInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string activity_type = 1;</code>
     */
    protected $activity_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $activity_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Sdk\Core\CoreInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string activity_type = 1;</code>
     * @return string
     */
    public function getActivityType()
    {
        return $this->activity_type;
    }

    /**
     * Generated from protobuf field <code>string activity_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->activity_type = $var;

        return $this;
    }

}

