<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/sdk/core/core_interface.proto

namespace Coresdk;

if (false) {
    /**
     * This class is deprecated. Use Coresdk\NamespaceInfo\Limits instead.
     * @deprecated
     */
    class NamespaceInfo_Limits {}
}
class_exists(NamespaceInfo\Limits::class);
@trigger_error('Coresdk\NamespaceInfo_Limits is deprecated and will be removed in the next major release. Use Coresdk\NamespaceInfo\Limits instead', E_USER_DEPRECATED);

